// AUTO-GENERATED by scripts/import-wave1-drafts.mjs (Wave 1 launch 2026-06-12).
// Edit drafts in /mnt/user-uploads and re-run the script rather than editing
// this file by hand. Native review status carried via the `nativeReview` field.
import type { BlogArticle } from './blogArticles';

/** Language-support FAQ answer reused wherever the "service in this language?" note appears. */
export const PA_LANGUAGE_NOTE = `honestly, team English ਵਿੱਚ service ਦਿੰਦੀ ਹੈ। ਫ਼ਿਕਰ ਨਾ ਕਰੋ: friend ਜਾਂ family member English speaker ਲੈ ਕੇ ਆਓ, ਜਾਂ translation app use ਕਰੋ। ਅਸੀਂ patient ਰੱਖਾਂਗੇ, ਕੰਮ ਜ਼ਰੂਰ ਹੋਵੇਗਾ।`;

interface Wave1Article extends BlogArticle {
  /** Wave 1 native-review status. 'pending' until a native speaker signs off. */
  nativeReview?: 'pending' | 'reviewed';
  /** Original draft frontmatter internalLinks for audit. */
  internalLinks?: string[];
  /** Original draft frontmatter officialSources for audit. */
  officialSources?: string[];
}

export const punjabiBlogArticles: Wave1Article[] = [
  {
    slug: 'ontario-fishing-licence-punjabi-guide',
    title: 'Ontario Fishing Licence ki hai te kiven laiye | ਓਨਟਾਰੀਓ ਫਿਸ਼ਿੰਗ ਲਾਇਸੰਸ ਗਾਈਡ',
    seoTitle: 'Ontario Fishing Licence ki hai te kiven laiye | ਓਨਟਾਰੀਓ ਫਿਸ਼ਿੰਗ ਲਾਇਸੰਸ ਗਾਈਡ',
    description: 'Ontario fishing licence ki kiven laiye? Outdoors Card, conservation vs sport licence, FMZ 17 Rice Lake rules te free Learn to Fish program, sab Punjabi vich.',
    image: '/lovable-uploads/hero-boat-rental-licence-ontario.webp',
    author: 'Harris Boat Works',
    datePublished: '2026-06-12',
    dateModified: '2026-08-01',
    category: 'ਪੰਜਾਬੀ ਗਾਈਡ',
    readTime: '8 ਮਿੰਟ',
    keywords: ['Ontario fishing license keemat online (Ontario fishing license price online)', 'Toronto de nere fishing spots family layi (fishing spots near Toronto for family)', 'fishing seasons Ontario 2024 Punjabi (fishing seasons Ontario 2024 Punjabi)', 'Rice Lake fishing rules limits Punjabi (Rice Lake fishing rules and limits in Punjabi)', 'Brampton waale fishing spot ki ne Punjabi (what are the fishing spots for Brampton people in Punjabi)', 'Kawartha lakes fishing map Punjabi video (Kawartha lakes fishing map Punjabi video)'],
    faqs: [
      { question: '1. Ontario fishing license di keemat kinna hai online?', answer: 'licence ਦੀ ਫ਼ੀਸ structure ’ਤੇ ਨਿਰਭਰ ਕਰਦੀ ਹੈ: Outdoors Card ਦੀ ਆਪਣੀ ਫ਼ੀਸ, ਅਤੇ fishing licence (conservation ਜਾਂ sport) ਦੀ ਵੱਖ। ਫ਼ੀਸਾਂ official page ’ਤੇ ਹੀ ਤਾਜ਼ਾ ਰਹਿੰਦੀਆਂ ਹਨ, ਕਿਰਪਾ ਕਰਕੇ ਇਸਦਾ ਅੰਦਾਜ਼ਾ ਨਾ ਲਗਾਓ। ਇਹ ਲਿੰਕ ਖੋਲ੍ਹੋ: https://www.ontario.ca/document/ontario-fishing-regulations-summary/recreational-fishing-licences-and-fees।' },
      { question: '2. Toronto de nere family layi fishing spots kaun se ne?', answer: 'Rice Lake, Gores Landing ’ਤੇ, Toronto area ਤੋਂ 90 ਮਿੰਟ ਦੀ drive ’ਤੇ, ਪਰਿਵਾਰਾਂ ਲਈ ਬਹੁਤ ਵਧੀਆ ਹੈ। HBW ਕੋਲ pontoon ਅਤੇ fishing boat rental fleet ਹੈ; ਮੌਜੂਦਾ fleet ਅਤੇ availability harrisboatworks.ca/rentals ’ਤੇ ਵੇਖੋ। Ethanol-free fuel site ’ਤੇ ਹੈ, ਅਤੇ ਮਾਹੌਲ family-friendly ਹੈ।' },
      { question: '3. Fishing seasons Ontario vich kiven pata lagge?', answer: 'FMZ 17 (Rice Lake ਦਾ ਜ਼ੋਨ) ਲਈ Ontario Fishing Regulations Summary online ਵੇਖੋ: https://www.ontario.ca/document/ontario-fishing-regulations-summary। ਹਰ species ਲਈ season ਖੁੱਲ੍ਹਣ-ਬੰਦ ਹੋਣ ਦੀਆਂ dates, size limits, slot sizes, ਸਭ official summary ਤੋਂ ਮਿਲਦਾ ਹੈ। ਇਸ ’ਤੇ trust ਕਰੋ, ਕਿਸੇ older video ’ਤੇ ਨਹੀਂ।' },
      { question: '4. Rice Lake te fishing rules limits ki ne?', answer: 'rule structure ਇਹ ਹੈ: conservation licence ’ਤੇ daily catch limit sport licence ਨਾਲੋਂ ਘੱਟ; size limit species ਮੁਤਾਬਕ; slot size (walleye, muskellunge) ’ਵੇਖਣੀ ਪੈਂਦੀ ਹੈ। official summary FMZ 17 section ਵਿੱਚ ਹਰ species ਵੱਖ-ਵੱਖ rules ਦਿੱਤੇ ਹਨ। numbers ਅਗਲੀ trip ਤੋਂ ਪਹਿਲਾਂ official ਸਰੋਤ ਤੋਂ ਜ਼ਰੂਰ check ਕਰੋ।' },
      { question: '5. Brampton ton fishing spot kidhar jaayiye?', answer: 'Brampton ਤੋਂ Gores Landing, Rice Lake 90 ਮਿੰਟ ਲੱਗਦੇ ਹਨ। Highway 401 ਪੂਰਬ, Highway 115/35 ਉੱਤਰ, ਫ਼ਿਰ County Rd 18। Gores Landing Harris Boat Works Rd ’ਤੇ parking site ’ਤੇ ਹੈ। rentals page ’ਤੇ plan ਬਣਾਓ: https://harrisboatworks.ca/rentals।' },
      { question: '6. Kya mainu Harris Boat Works te Punjabi vich service mil sakdi hai?', answer: 'honestly, team English ਵਿੱਚ service ਦਿੰਦੀ ਹੈ। ਫ਼ਿਕਰ ਨਾ ਕਰੋ: friend ਜਾਂ family member English speaker ਲੈ ਕੇ ਆਓ, ਜਾਂ translation app use ਕਰੋ। ਅਸੀਂ patient ਰੱਖਾਂਗੇ, ਕੰਮ ਜ਼ਰੂਰ ਹੋਵੇਗਾ।' },
      { question: '7. Kids layi fishing licence di lod hai?', answer: 'Ontario residents under 18 ਨੂੰ Outdoors Card ਜਾਂ fishing licence ਨਹੀਂ ਲੈਣੀ ਪੈਂਦੀ, ਪਰ rules limits ਜ਼ਰੂਰ follow ਕਰਨੇ ਪੈਂਦੇ ਹਨ। non-resident minors ਲਈ rules ਜ਼ਰਾ different ਹਨ, official page ’ਤੇ confirm ਕਰੋ: https://www.ontario.ca/page/fishing-licence-ontario-and-canadian-residents।' },
      { question: '8. Kawartha lakes fishing map video Punjabi vich mildi hai?', answer: 'video availability Punjabi ਵਿੱਚ official ਤੌਰ ’ਤੇ ਨਹੀਂ, ਪਰ Ontario government fishing map interactive online ਹੈ। Rice Lake ਨੂੰ Kawarthas ਵਿੱਚ select ਕਰਕੇ spots ’ਤੇ information ਮਿਲ ਜਾਵੇਗੀ। regulations summary ਜ਼ਰੂਰ read ਕਰੋ।' }
    ],
    nativeReview: 'pending',
    internalLinks: ['https://harrisboatworks.ca/rentals', 'https://hbw.wiki/service'],
    officialSources: ['https://www.ontario.ca/page/fishing-licence-ontario-and-canadian-residents', 'https://www.ontario.ca/page/fishing-licence-non-residents-canada', 'https://www.ontario.ca/page/get-outdoors-card-and-licence-summary', 'https://www.ontario.ca/document/ontario-fishing-regulations-summary', 'https://www.ontario.ca/document/ontario-fishing-regulations-summary/recreational-fishing-licences-and-fees', 'https://www.ontario.ca/page/learn-fish'],
    content: `ਜੇ ਤੁਸੀਂ Brampton, Mississauga, Scarborough ਜਾਂ Markham ਤੋਂ Rice Lake ਉੱਤੇ ਮੱਛੀ ਫੜਨ ਦੀ ਸੋਚ ਰਹੇ ਹੋ, ਤਾਂ ਇਹ ਗਾਈਡ ਤੁਹਾਡੀ ਮਦਦ ਕਰੇਗੀ। Rice Lake, Gores Landing ’ਤੇ ਸਾਡੀ ਮਰੀਨਾ ਤੋਂ ਲਗਭਗ 90 ਮਿੰਟ ਦੀ ਡਰਾਈਵ ਹੈ। ਪਰਿਵਾਰ ਨਾਲ ਮਜ਼ੇਦਾਰ ਦਿਨ ਬਤੀਤ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ, Ontario ਦੇ fishing licence ਦੇ ਨਿਯਮਾਂ ਨੂੰ ਸਮਝਣਾ ਜ਼ਰੂਰੀ ਹੈ। ਸਾਡੀ family marina ਨੂੰ ਤੀਜੀ ਪੀੜ੍ਹੀ ਚਲਾ ਰਹੀ ਹੈ, 1947 ਤੋਂ ਇਸੇ ਝੀਲ ਕੰਢੇ ਹਾਂ, ਅਤੇ Punjabi ਭਾਈਚਾਰੇ ਦੇ ਪਰਿਵਾਰਾਂ ਨੂੰ Rice Lake ਦਾ ਆਨੰਦ ਲੈਂਦੇ ਦੇਖਣਾ ਸਾਨੂੰ ਚੰਗਾ ਲੱਗਦਾ ਹੈ। ਇਸ ਪੇਜ ਵਿੱਚ, ਅਸੀਂ ਬਿਨਾਂ ਕਿਸੇ ਔਖੀ ਕਾਨੂੰਨੀ ਭਾਸ਼ਾ ਦੇ, fishing licence, Outdoors Card, conservation licence ਬਨਾਮ sport licence, FMZ 17, ਅਤੇ ਪਹਿਲੀ ਯਾਤਰਾ ਦੀ ਤਿਆਰੀ ਬਾਰੇ ਸਮਝਾਵਾਂਗੇ।

## Outdoors Card te licence di buniyad | ਆਊਟਡੋਰਸ ਕਾਰਡ ਤੇ ਲਾਇਸੰਸ ਦੀ ਬੁਨਿਆਦ

Ontario ਵਿੱਚ, 18 ਤੋਂ 64 ਸਾਲ ਦੇ residents ਅਤੇ ਜ਼ਿਆਦਾਤਰ visitors ਨੂੰ ਮੱਛੀ ਫੜਨ ਲਈ fishing licence ਲੈਣੀ ਪੈਂਦੀ ਹੈ। ਪਰ ਇਹ ਸਿਰਫ ਇੱਕ ਕਾਗਜ਼ ਨਹੀਂ: ਤੁਹਾਨੂੰ ਪਹਿਲਾਂ Outdoors Card ਬਣਾਉਣੀ ਪੈਂਦੀ ਹੈ। Outdoors Card ਇੱਕ ਪਲਾਸਟਿਕ ਕਾਰਡ ਹੈ ਜੋ ਤੁਹਾਡੀ ਪਛਾਣ ਨੰਬਰ ਰੱਖਦਾ ਹੈ, ਅਤੇ ਫਿਰ ਤੁਸੀਂ ਇਸ ’ਤੇ fishing licence ਜੋੜਦੇ ਹੋ, ਇਹ sticker ਜਾਂ ਇਲੈਕਟ੍ਰਾਨਿਕ ਫਾਰਮੈਟ ਵਿੱਚ ਹੋ ਸਕਦੀ ਹੈ। ਮੋਟੇ ਤੌਰ ’ਤੇ ਦੋ ਤਰ੍ਹਾਂ ਦੀ fishing licence ਹੁੰਦੀ ਹੈ: conservation licence ਅਤੇ sport fishing licence। conservation licence ਨਾਲ ਤੁਹਾਡੀ daily catch limit ਘੱਟ ਹੁੰਦੀ ਹੈ, ਪਰ ਫ਼ੀਸ ਵੀ ਘੱਟ ਹੁੰਦੀ ਹੈ। sport licence ਨਾਲ limit ਜ਼ਿਆਦਾ ਹੈ ਅਤੇ ਫ਼ੀਸ ਵੀ ਜ਼ਿਆਦਾ। Rice Lake ’ਤੇ ਮੱਛੀਆਂ ਲਈ ਦੋਵਾਂ ਦੀ limit, species ਅਤੇ season ਅਨੁਸਾਰ ਵੱਖ-ਵੱਖ ਹੁੰਦੀ ਹੈ।

ਧਿਆਨ ਰੱਖੋ: ਅਸੀਂ ਇੱਥੇ ਫ਼ੀਸਾਂ ਦੀ ਕੋਈ ਖਾਸ ਰਕਮ ਨਹੀਂ ਦੱਸ ਸਕਦੇ, ਕਿਉਂਕਿ ਇਹ ਬਦਲ ਸਕਦੀ ਹੈ। ਸਹੀ ਫ਼ੀਸਾਂ ਲਈ Ontario government ਦਾ official fees page ਦੇਖੋ: https://www.ontario.ca/document/ontario-fishing-regulations-summary/recreational-fishing-licences-and-fees। ਇਹ ਸਾਰੀ ਜਾਣਕਾਰੀ ਆਮ ਸਮਝਾਉਣ ਲਈ ਹੈ, ਕਾਨੂੰਨੀ ਸਲਾਹ ਨਹੀਂ। ਨਿਯਮ ਬਦਲਦੇ ਰਹਿੰਦੇ ਹਨ, ਇਸ ਲਈ official ਸਰੋਤ ਹਮੇਸ਼ਾ ਜਿੱਤਦਾ ਹੈ।

## Kiven online laiye | ਕਿਵੇਂ ਔਨਲਾਈਨ ਲਈਏ

licence online ਲੈਣਾ ਸੌਖਾ ਹੈ, ਪਰ ਕੁਝ ਕਦਮ ਹਨ। Ontario residents ਅਤੇ non-residents ਦੋਵੇਂ Ontario.ca ’ਤੇ ਜਾ ਕੇ ਆਪਣੀ Outdoors Card ਅਤੇ fishing licence ਖ਼ਰੀਦ ਸਕਦੇ ਹਨ। ਇੱਕ ਵਾਰ Outdoors Card ਨੰਬਰ ਮਿਲ ਜਾਵੇ, ਤੁਸੀਂ ਇੱਕ ਸਾਲ, ਤਿੰਨ ਸਾਲ, ਜਾਂ ਕੁਝ ਹੋਰ ਮਿਆਦ ਵਾਲੀ licence ਖਰੀਦ ਸਕਦੇ ਹੋ। ਫ਼ੀਸਾਂ species ਦੀ limit ਤਹਿਤ ਹੀ official page ’ਤੇ ਹੀ ਮਿਲਣਗੀਆਂ, ਅਸੀਂ ਇੱਥੇ ਗਿਣਤੀ ਨਹੀਂ ਦੱਸਾਂਗੇ। ਖ਼ਰੀਦਣ ਤੋਂ ਬਾਅਦ, licence ਦਾ ਡਿਜੀਟਲ version ਆਪਣੇ ਫ਼ੋਨ ’ਤੇ ਰੱਖੋ, ਜਾਂ ਪ੍ਰਿੰਟ ਕਰੋ। ਮੱਛੀ ਫੜਦੇ ਸਮੇਂ government ID ਨਾਲ ਰੱਖੋ। official steps ਲਈ: https://www.ontario.ca/page/get-outdoors-card-and-licence-summary।

## Rice Lake te FMZ 17 | ਰਾਈਸ ਲੇਕ ਤੇ FMZ 17

Rice Lake Fisheries Management Zone 17 (FMZ 17) ਵਿੱਚ ਆਉਂਦੀ ਹੈ। Ontario ਨੂੰ 20 ਜ਼ੋਨਾਂ ਵਿੱਚ ਵੰਡਿਆ ਗਿਆ ਹੈ, ਹਰ ਜ਼ੋਨ ਵਿੱਚ ਹਰ ਮੱਛੀ ਲਈ ਵੱਖ season, size limit ਅਤੇ daily limit ਹੁੰਦੀ ਹੈ। Rice Lake ਵਿੱਚ walleye, bass, muskie, panfish ਤੇ ਹੋਰ ਮਿਲਦੀਆਂ ਹਨ, ਹਰ ਇੱਕ ਦੇ ਆਪਣੇ rules। ਅਸੀਂ ਇੱਥੇ ਕੋਈ ਖ਼ਾਸ ਮਿਤੀ ਜਾਂ limit ਨਹੀਂ ਦੱਸ ਸਕਦੇ, ਕਿਉਂਕਿ ਇਹ ਗਲਤ ਹੋ ਸਕਦਾ ਹੈ। ਬਚਾਓ ਲਈ, Ontario Fishing Regulations Summary ਹਮੇਸ਼ਾ ਤਾਜ਼ਾ ਰਹਿੰਦੀ ਹੈ: https://www.ontario.ca/document/ontario-fishing-regulations-summary। ਇਸਨੂੰ ਖੋਲ੍ਹੋ, FMZ 17 ਲੱਭੋ, ਅਤੇ ਜੋ ਮੱਛੀ ਤੁਸੀਂ ਫੜਨੀ ਹੈ, ਉਸ ਦਾ season ਖੁੱਲ੍ਹਾ ਹੈ ਜਾਂ ਨਹੀਂ, limit ਕੀ ਹੈ, size ਕਿੰਨੀ ਹੋਣੀ ਚਾਹੀਦੀ, ਸਭ ਪਤਾ ਲੱਗ ਜਾਵੇਗਾ। conservation licence ’ਤੇ ਹਰ species ਦੀ limit sport licence ਨਾਲੋਂ ਘੱਟ ਹੁੰਦੀ ਹੈ, ਇਹ ਜ਼ਰੂਰ ਚੈੱਕ ਕਰੋ।

## Learn to Fish program bare | ਲਰਨ ਟੂ ਫਿਸ਼ ਪ੍ਰੋਗਰਾਮ ਬਾਰੇ

ਜੇਕਰ ਤੁਹਾਡਾ ਪਰਿਵਾਰ ਮੱਛੀ ਫੜਨ ਵਿੱਚ ਬਿਲਕੁਲ ਨਵਾਂ ਹੈ, ਤਾਂ Ontario government ਦਾ Learn to Fish program ਬਹੁਤ ਵਧੀਆ ਹੈ। ਇਹ free 2-ਘੰਟੇ ਦੇ session ਹੁੰਦੇ ਹਨ, gear government ਮੁਹੱਈਆ ਕਰਦੀ ਹੈ। ਇਹ session ਸਾਡੀ ਮਰੀਨਾ ’ਤੇ ਨਹੀਂ ਹੁੰਦੇ, Ontario ਦੀਆਂ ਕਈ ਹੋਰ ਥਾਵਾਂ ’ਤੇ ਹਨ। ਜ਼ਿਆਦਾ ਜਾਣਕਾਰੀ: https://www.ontario.ca/page/learn-fish। ਬੱਚੇ ਤੇ ਨਵੇਂ anglers ਇੱਥੇ ਬੇਝਿਜਕ basic skills ਸਿੱਖ ਸਕਦੇ ਹਨ।

## Pehli trip layi checklist | ਪਹਿਲੀ ਯਾਤਰਾ ਲਈ ਚੈਕਲਿਸਟ

Rice Lake ’ਤੇ Gores Landing ਆ ਕੇ ਕਿਸ਼ਤੀ ਕਿਰਾਏ ’ਤੇ ਲੈ ਕੇ, ਜਾਂ ਕੰਢੇ ਤੋਂ ਮੱਛੀ ਫੜਨ ਤੋਂ ਪਹਿਲਾਂ, ਇਹ ਜ਼ਰੂਰ ਲੈ ਜਾਓ:
- Outdoors Card ਅਤੇ fishing licence (ਡਿਜੀਟਲ ਜਾਂ print)
- Valid government ID
- FMZ 17 ਦਾ regulations summary ਫ਼ੋਨ ਵਿੱਚ save ਕੀਤਾ ਹੋਇਆ
- ਮੌਸਮ ਮੁਤਾਬਕ ਕੱਪੜੇ, sun protection
- Life jacket: ਜੇਕਰ ਤੁਸੀਂ ਸਾਡੀ rental boat ਲੈਂਦੇ ਹੋ, life jackets ਅਸੀਂ ਦਿੰਦੇ ਹਾਂ। ਫਿਰ ਵੀ, ਛੋਟੇ ਬੱਚਿਆਂ ਲਈ ਆਪਣਾ well-fitted jacket ਲੈ ਕੇ ਆਉਣਾ ਚੰਗਾ।
- Snacks ਤੇ ਪਾਣੀ, camera, ਅਤੇ patience!

## Saadi team de service baare ik imaandaari wali gall | ਸਾਡੀ ਟੀਮ ਦੀ ਸੇਵਾ ਬਾਰੇ ਇਕ ਈਮਾਨਦਾਰੀ ਵਾਲੀ ਗੱਲ

ਅਸੀਂ ਇਹ ਗਾਈਡ Punjabi ਵਿੱਚ ਇਸ ਲਈ ਬਣਾਈ ਹੈ ਕਿਉਂਕਿ ਅਸੀਂ ਸੱਚਮੁੱਚ Punjabi ਭਾਈਚਾਰੇ ਦੇ boaters ਅਤੇ ਉਨ੍ਹਾਂ ਦੇ ਪਰਿਵਾਰਾਂ ਅਤੇ ਦੋਸਤਾਂ ਦੀ Rice Lake ਦਾ ਆਨੰਦ ਲੈਣ ਵਿੱਚ ਮਦਦ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹਾਂ, ਕੁਝ ਅਜਿਹਾ ਜੋ ਬਹੁਤ ਘੱਟ ਲੋਕਾਂ ਨੇ ਕੀਤਾ ਹੈ। ਇਸ ਛੋਟੇ ਜਿਹੇ effort ਨਾਲ, ਅਸੀਂ ਚਾਹੁੰਦੇ ਹਾਂ ਕਿ ਪਹਿਲੀ ਵਾਰੀ ਨਾ-ਜਾਣਿਆਂ ਪਰਿਵਾਰ comfortable ਮਹਿਸੂਸ ਕਰੇ।

ਇਮਾਨਦਾਰੀ ਦੀ ਗੱਲ: ਸਾਡੀ team English ਵਿੱਚ service ਦਿੰਦੀ ਹੈ। ਪਰ ਫ਼ਿਕਰ ਨਾ ਕਰੋ: ਨਾਲ ਕੋਈ friend ਜਾਂ family member ਲੈ ਕੇ ਆਓ ਜੋ English ਬੋਲ ਸਕਦਾ ਹੈ, ਜਾਂ ਆਪਣੇ ਫ਼ੋਨ ’ਤੇ translation app use ਕਰੋ। ਅਸੀਂ ਸਬਰ ਨਾਲ ਕੰਮ ਕੱਢ ਲਵਾਂਗੇ। ਬੱਸ ਆਓ Harris Boat Works ’ਤੇ, ਅਸੀਂ ਮਿਲ ਕੇ arrangement ਬਣਾ ਲਵਾਂਗੇ।

## Aksar puchhe jaande sawaal | FAQ

**1. Ontario fishing license di keemat kinna hai online?**  
licence ਦੀ ਫ਼ੀਸ structure ’ਤੇ ਨਿਰਭਰ ਕਰਦੀ ਹੈ: Outdoors Card ਦੀ ਆਪਣੀ ਫ਼ੀਸ, ਅਤੇ fishing licence (conservation ਜਾਂ sport) ਦੀ ਵੱਖ। ਫ਼ੀਸਾਂ official page ’ਤੇ ਹੀ ਤਾਜ਼ਾ ਰਹਿੰਦੀਆਂ ਹਨ, ਕਿਰਪਾ ਕਰਕੇ ਇਸਦਾ ਅੰਦਾਜ਼ਾ ਨਾ ਲਗਾਓ। ਇਹ ਲਿੰਕ ਖੋਲ੍ਹੋ: https://www.ontario.ca/document/ontario-fishing-regulations-summary/recreational-fishing-licences-and-fees।

**2. Toronto de nere family layi fishing spots kaun se ne?**  
Rice Lake, Gores Landing ’ਤੇ, Toronto area ਤੋਂ 90 ਮਿੰਟ ਦੀ drive ’ਤੇ, ਪਰਿਵਾਰਾਂ ਲਈ ਬਹੁਤ ਵਧੀਆ ਹੈ। HBW ਕੋਲ pontoon ਅਤੇ fishing boat rental fleet ਹੈ; ਮੌਜੂਦਾ fleet ਅਤੇ availability harrisboatworks.ca/rentals ’ਤੇ ਵੇਖੋ। Ethanol-free fuel site ’ਤੇ ਹੈ, ਅਤੇ ਮਾਹੌਲ family-friendly ਹੈ।

**3. Fishing seasons Ontario vich kiven pata lagge?**  
FMZ 17 (Rice Lake ਦਾ ਜ਼ੋਨ) ਲਈ Ontario Fishing Regulations Summary online ਵੇਖੋ: https://www.ontario.ca/document/ontario-fishing-regulations-summary। ਹਰ species ਲਈ season ਖੁੱਲ੍ਹਣ-ਬੰਦ ਹੋਣ ਦੀਆਂ dates, size limits, slot sizes, ਸਭ official summary ਤੋਂ ਮਿਲਦਾ ਹੈ। ਇਸ ’ਤੇ trust ਕਰੋ, ਕਿਸੇ older video ’ਤੇ ਨਹੀਂ।

**4. Rice Lake te fishing rules limits ki ne?**  
rule structure ਇਹ ਹੈ: conservation licence ’ਤੇ daily catch limit sport licence ਨਾਲੋਂ ਘੱਟ; size limit species ਮੁਤਾਬਕ; slot size (walleye, muskellunge) ’ਵੇਖਣੀ ਪੈਂਦੀ ਹੈ। official summary FMZ 17 section ਵਿੱਚ ਹਰ species ਵੱਖ-ਵੱਖ rules ਦਿੱਤੇ ਹਨ। numbers ਅਗਲੀ trip ਤੋਂ ਪਹਿਲਾਂ official ਸਰੋਤ ਤੋਂ ਜ਼ਰੂਰ check ਕਰੋ।

**5. Brampton ton fishing spot kidhar jaayiye?**  
Brampton ਤੋਂ Gores Landing, Rice Lake 90 ਮਿੰਟ ਲੱਗਦੇ ਹਨ। Highway 401 ਪੂਰਬ, Highway 115/35 ਉੱਤਰ, ਫ਼ਿਰ County Rd 18। Gores Landing Harris Boat Works Rd ’ਤੇ parking site ’ਤੇ ਹੈ। rentals page ’ਤੇ plan ਬਣਾਓ: https://harrisboatworks.ca/rentals।

**6. Kya mainu Harris Boat Works te Punjabi vich service mil sakdi hai?**  
honestly, team English ਵਿੱਚ service ਦਿੰਦੀ ਹੈ। ਫ਼ਿਕਰ ਨਾ ਕਰੋ: friend ਜਾਂ family member English speaker ਲੈ ਕੇ ਆਓ, ਜਾਂ translation app use ਕਰੋ। ਅਸੀਂ patient ਰੱਖਾਂਗੇ, ਕੰਮ ਜ਼ਰੂਰ ਹੋਵੇਗਾ।

**7. Kids layi fishing licence di lod hai?**  
Ontario residents under 18 ਨੂੰ Outdoors Card ਜਾਂ fishing licence ਨਹੀਂ ਲੈਣੀ ਪੈਂਦੀ, ਪਰ rules limits ਜ਼ਰੂਰ follow ਕਰਨੇ ਪੈਂਦੇ ਹਨ। non-resident minors ਲਈ rules ਜ਼ਰਾ different ਹਨ, official page ’ਤੇ confirm ਕਰੋ: https://www.ontario.ca/page/fishing-licence-ontario-and-canadian-residents।

**8. Kawartha lakes fishing map video Punjabi vich mildi hai?**  
video availability Punjabi ਵਿੱਚ official ਤੌਰ ’ਤੇ ਨਹੀਂ, ਪਰ Ontario government fishing map interactive online ਹੈ। Rice Lake ਨੂੰ Kawarthas ਵਿੱਚ select ਕਰਕੇ spots ’ਤੇ information ਮਿਲ ਜਾਵੇਗੀ। regulations summary ਜ਼ਰੂਰ read ਕਰੋ।

## Harris Boat Works ton madad lai link | ਹੈਰਿਸ ਬੋਟ ਵਰਕਸ ਤੋਂ ਮਦਦ ਲਈ ਲਿੰਕ

Rice Lake ’ਤੇ fishing day plan ਕਰ ਰਹੇ ਹੋ? ਸਾਡੀ rental boat book ਕਰੋ: https://harrisboatworks.ca/rentals  
service ਦੀ ਲੋੜ ਹੈ? service requests online: https://hbw.wiki/service  
phone: (905) 342-2153  
text: (647) 952-2153  
address: 5369 Harris Boat Works Rd, Gores Landing, ON K0K 2E0

Harris Boat Works 1947 ਤੋਂ family-owned marina ਹੈ, Mercury ਡੀਲਰ 1965 ਤੋਂ, Premier Dealer। winter (1 Dec ਤੋਂ 1 Apr) ਅਸੀਂ closed ਹੁੰਦੇ ਹਾਂ। ਫ਼ਿਰ spring ’ਚ ਜ਼ਰੂਰ ਆਉਣਾ।`
  },
  {
    slug: 'boat-licence-rental-ontario-punjabi-pcoc-faq',
    title: 'Ontario vich boat chalaun layi licence chahida? PCOC FAQ | ਕਿਸ਼ਤੀ ਲਾਇਸੰਸ ਸਵਾਲ-ਜਵਾਬ',
    seoTitle: 'Ontario vich boat chalaun layi licence chahida? PCOC FAQ | ਕਿਸ਼ਤੀ ਲਾਇਸੰਸ ਸਵਾਲ-ਜਵਾਬ',
    description: 'Ki Ontario vich boat rent karan layi licence chahida? PCOC rules, bina card rental boat kiven chalao, lifejacket rules. Punjabi vich poori jaankari ethe lao.',
    image: '/lovable-uploads/hero-boat-rental-licence-ontario.webp',
    author: 'Harris Boat Works',
    datePublished: '2026-06-12',
    dateModified: '2026-06-12',
    category: 'ਪੰਜਾਬੀ ਗਾਈਡ',
    readTime: '8 ਮਿੰਟ',
    keywords: ['Ontario vich boat license kinj banaye (how to get a boat license in Ontario)', 'boat operator card zaroori hai Ontario vich (is boat operator card necessary in Ontario)', 'PCOC course online free Punjabi (PCOC course online free in Punjabi)', 'boat chalan layi license di lod hai Canada ch (do you need a license to drive a boat in Canada)'],
    faqs: [
      { question: 'Ontario vich boat chalaun lai license kinj banayiye?', answer: 'ਪਹਿਲਾਂ Transport Canada ਦੇ ਮਾਨਤਾ-ਪ੍ਰਾਪਤ ਪ੍ਰਦਾਤਾਵਾਂ ਰਾਹੀਂ online PCOC ਕੋਰਸ ਕਰੋ। exam pass ਕਰੋ, card lifetime ਲਈ ਮਿਲ ਜਾਵੇਗਾ। official list: https://tc.canada.ca/en/marine-transportation/buying-boat/find-education-resources-recreational-boaters' },
      { question: 'Je main ik din layi boat rent karan, PCOC deni paini hai?', answer: 'ਨਹੀਂ, temporary rental boat safety checklist ’ਤੇ ਦਸਤਖਤ ਕਰਕੇ boat rent ਲੈ ਸਕਦੇ ਹੋ। Harris Boat Works ਦੀ rental fleet ਲਈ ਸਿੱਧਾ https://harrisboatworks.ca/rentals ’ਤੇ ਜਾਓ, full briefing ਮਿਲੇਗੀ।' },
      { question: 'Kya “boat license” te “boat operator card” different hunde ne?', answer: 'Boat license (PCL) boat ਦੀ registration number ਹੈ; operator card (PCOC) ਤੁਹਾਡੀ training ਦਾ ਸਬੂਤ ਹੈ। ਦੋਵੇਂ ਵਕਤ confuse ਨਾ ਹੋ, official terms PCL ਤੇ PCOC ਯਾਦ ਰੱਖੋ।' },
      { question: 'PCOC course online muft Punjabi vich mil sakda ae?', answer: 'ਮੁਫ਼ਤ ਦਾ ਨਹੀਂ ਪਤਾ, course providers ਕੀਮਤ ਮੰਗਣਗੇ, ਅਤੇ course English ਜਾਂ French ਵਿੱਚ ਹੀ officially available ਹੈ। Punjabi ਵਿੱਚ approved version Transport Canada ਨਹੀਂ ਰੱਖਿਆ। Phone application translation ਨਾਲ study ਆਸਾਨ ਹੋ ਸਕਦਾ ਹੈ।' },
      { question: 'Mere chacha ji apni boat leke Ontario aaye; kya oh bina card de chala sakde?', answer: 'ਨਹੀਂ, motor boat operate ਕਰਨ ਲਈ valid PCOC ਹੋਣੀ ਚਾਹੀਦੀ, ਨਹੀਂ ਤਾਂ officer penalty ਲਾ ਸਕਦਾ। Temporary visitor ਵੀ online course ਕੀਤਾ ਜਾ ਸਕਦਾ, ਇਸ ਲਈ planning ਕਰਕੇ ਆਓ।' },
      { question: 'Ki Harris Boat Works te Punjabi vich service mildi hai?', answer: 'ਇਹ guide Punjabi ਵਿੱਚ ਲਿਖੀ ਸੀ, ਪਰ ਸਾਡੀ ਸੇਵਾ English ਵਿੱਚ ਹੀ ਚੱਲਦੀ ਹੈ। ਨਾਲ English ਦਾ ਬੰਦਾ ਲੈ ਆਓ ਜਾਂ phone translate ਵਰਤੋ, ਅਸੀਂ ਰੁਕ ਕੇ ਸਮਝਾਵਾਂਗੇ, ਕੋਈ ਮੁਸ਼ਕਲ ਨਹੀਂ। (ਉੱਪਰ ਵਾਲੀ ਇਮਾਨਦਾਰੀ ਵਾਲੀ ਗੱਲ ਵੇਖ ਲਓ।)' }
    ],
    nativeReview: 'pending',
    internalLinks: ['https://harrisboatworks.ca/rentals'],
    officialSources: ['https://tc.canada.ca/en/marine-transportation/preparing-operate-your-vessel/pleasure-craft-operator-card-pcoc', 'https://tc.canada.ca/en/marine-transportation/buying-boat/find-education-resources-recreational-boaters'],
    content: `ਜਵਾਬ ਪਹਿਲਾਂ: Ontario ਵਿੱਚ ਕੋਈ ਵੀ ਮੋਟਰ ਵਾਲੀ ਕਿਸ਼ਤੀ (power-driven boat) ਚਲਾਉਣ ਲਈ ਤੁਹਾਡੇ ਕੋਲ PCOC (Pleasure Craft Operator Card) ਹੋਣਾ ਲਾਜ਼ਮੀ ਹੈ। ਇਹ ਕਾਰਡ-ਵਰਗਾ ਸਰਟੀਫਿਕੇਟ ਹੈ, ਜਿਵੇਂ ਕਾਰ ਚਲਾਉਣ ਲਈ ਡਰਾਈਵਿੰਗ ਲਾਇਸੰਸ। ਮਾਮੂਲੀ ਪੈਡਲ ਬੋਟਾਂ, ਕਾਇਆਕ, ਜਾਂ ਕੈਨੂਆਂ ਲਈ PCOC ਦੀ ਲੋੜ ਨਹੀਂ, ਬੱਸ ਜੇ ਉਹਨਾਂ ’ਤੇ ਕੋਈ ਮੋਟਰ ਲੱਗੀ ਹੋਵੇ। ਜੇ ਤੁਸੀਂ ਸਾਡੇ ਕੋਲੋਂ ਕਿਸ਼ਤੀ ਕਿਰਾਏ ’ਤੇ ਲੈ ਰਹੇ ਹੋ, ਤਾਂ ਇੱਕ ਆਰਜ਼ੀ ਕਿਰਾਏ ਦੀ ਕਿਸ਼ਤੀ ਸੁਰੱਖਿਆ ਜਾਂਚ-ਪੱਤਰ (temporary rental boat safety checklist) ਵੀ ਵਰਤੀ ਜਾ ਸਕਦੀ ਹੈ, ਇਸ ਬਾਰੇ ਥੱਲੇ ਵਿਸਥਾਰ ਨਾਲ ਦੱਸਿਆ ਗਿਆ ਹੈ।


ਨੋਟ: ਇਹ page ਸਿਰਫ਼ ਆਮ ਜਾਣਕਾਰੀ ਲਈ ਹੈ, legal advice ਨਹੀਂ। Rules ਬਦਲ ਸਕਦੇ ਹਨ; ਆਖ਼ਰੀ ਗੱਲ ਹਮੇਸ਼ਾ Transport Canada ਦੇ official ਸਫ਼ੇ ਦੀ ਮੰਨੋ: https://tc.canada.ca/en/marine-transportation/preparing-operate-your-vessel/pleasure-craft-operator-card-pcoc

## PCOC ਕੀ ਹੈ ਤੇ ਇਹ ਕਾਹਨੂੰ ਵਰਤੀ ਦਾ? | What is PCOC and why is it needed?

PCOC ਇੱਕ ਜੀਵਨ-ਭਰ ਦੀ ਯੋਗਤਾ ਹੈ, ਜੋ ਇਹ ਸਾਬਤ ਕਰਦੀ ਹੈ ਕਿ ਤੁਹਾਨੂੰ ਪਾਣੀ ਸੁਰੱਖਿਆ ਨਿਯਮਾਂ, ਨੈਵੀਗੇਸ਼ਨ ਮੂਲ ਗੱਲਾਂ, ਅਤੇ ਐਮਰਜੈਂਸੀ ਪ੍ਰਕਿਰਿਆਵਾਂ ਦੀ ਸਮਝ ਹੈ। ਟ੍ਰੈਫ਼ਿਕ ਪੁਲਿਸ ਵਰਗੇ ਸਮੁੰਦਰੀ ਅਧਿਕਾਰੀ (marine police, OPP) ਪਾਣੀ ’ਤੇ ਇਹ ਕਾਰਡ ਦੇਖਣ ਦੀ ਮੰਗ ਕਰ ਸਕਦੇ ਹਨ। Ontario ਜਾਂ Canada ਦੀ ਕਿਸੇ ਵੀ ਝੀਲ, ਨਦੀ, ਜਾਂ ਨਹਿਰ ’ਤੇ ਮੋਟਰ ਬੋਟ ਚਲਾਉਣ ਸਮੇਂ ਇਹ ਫੜ ਕੇ ਰੱਖਣਾ ਜ਼ਰੂਰੀ ਹੈ, ਚਾਹੇ ਤੁਸੀਂ Brampton, Mississauga, Scarborough, ਜਾਂ Markham ਤੋਂ ਇੱਕ-ਦਿਨ ਦੀ ਯਾਤਰਾ ’ਤੇ Rice Lake (Gores Landing) ਆਏ ਹੋਵੋ। Harris Boat Works 1947 ਤੋਂ ਚੱਲ ਰਹੀ ਇੱਕ ਪਰਿਵਾਰਕ ਮਰੀਨਾ ਹੈ, Mercury dealer 1965 ਤੋਂ, ਅਸੀਂ ਰੋਜ਼ ਪਹਿਲੀ-ਵਾਰ ਆਉਣ ਵਾਲੇ ਕਿਸ਼ਤੀ ਚਾਲਕਾਂ ਨੂੰ ਇਹੋ ਸਮਝਾਉਂਦੇ ਹਾਂ।

## PCOC (operator card) ਤੇ PCL (boat licence) ‘ਚ ਫ਼ਰਕ | Difference between operator card and boat licence

ਇਹ ਭੁਲੇਖਾ ਬਹੁਤ ਸਾਰੇ ਨਵੇਂ ਆਉਣ ਵਾਲਿਆਂ ਨੂੰ ਹੁੰਦਾ ਹੈ। PCOC ਵਿਅਕਤੀ ਦੀ ਯੋਗਤਾ ਹੈ: ਇਹ ਦੱਸਦੀ ਹੈ ਕਿ ਤੁਹਾਨੂੰ ਕਿਸ਼ਤੀ ਚਲਾਉਣ ਦੀ ਸਿਖਲਾਈ ਮਿਲੀ ਹੈ। PCL (Pleasure Craft Licence) ਖ਼ੁਦ ਕਿਸ਼ਤੀ ਦੀ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਹੈ: ਜਿਵੇਂ ਕਾਰ ਦੀ ਨੰਬਰ ਪਲੇਟ, ਜੋ ਕਿਸ਼ਤੀ ’ਤੇ ਨੰਬਰ ਲਗਾਉਣ ਲਈ ਮਿਲਦੀ ਹੈ। PCL Transport Canada ਤੋਂ ਮੁਫ਼ਤ ਜਾਰੀ ਹੁੰਦੀ ਹੈ, ਜੇ ਕਿਸ਼ਤੀ 10 horsepower (10 HP) ਤੋਂ ਵੱਡੀ ਮੋਟਰ ਫਿੱਟ ਹੋਵੇ। PCOC ਜ਼ਰੂਰੀ ਨਿੱਜੀ ਕਾਰਡ ਹੈ, ਜੋ ਕਿਸ਼ਤੀ ਕਿਰਾਏ ’ਤੇ ਲੈਣ ਵਾਲੇ ਤੇ ਮਾਲਕ, ਦੋਹਾਂ ਲਈ ਲਾਜ਼ਮੀ ਹੈ। ਕਈ ਲੋਕ PCOC ਨੂੰ "boat license" ਆਖਦੇ ਹਨ, ਪਰ ਅਧਿਕਾਰਤ ਸ਼ਬਦ PCOC ਹੈ, ਇਹੋ ਵਾਕ police ਵਰਤਦੀ ਹੈ।

## ਬਿਨਾਂ PCOC ਦੇ boat rent ਕਰ ਸਕਦੇ ਹਾਂ? | Can I rent a boat without PCOC?

ਬਿਲਕੁਲ, ਸੁਰੱਖਿਆ ਢਾਂਚੇ ਅੰਦਰ। Ontario ਦਾ ਨਿਯਮ ਕਹਿੰਦਾ ਹੈ: ਕਿਰਾਏ ’ਤੇ ਕਿਸ਼ਤੀ ਦੇਣ ਵਾਲੀ ਕੰਪਨੀ ਆਪਣੇ ਗਾਹਕ ਨੂੰ PCOC ਦੇਖਣ ਦੀ ਬਜਾਏ ਇੱਕ ਆਰਜ਼ੀ ਕਿਰਾਏ ਦੀ ਕਿਸ਼ਤੀ ਸੁਰੱਖਿਆ ਜਾਂਚ-ਪੱਤਰ ’ਤੇ ਦਸਤਖਤ ਕਰਵਾ ਸਕਦੀ ਹੈ। ਇਹ ਜਾਂਚ-ਪੱਤਰ Transport Canada ਦੀ ਮਨਜ਼ੂਰਸ਼ੁਦਾ ਫਾਰਮ ਹੁੰਦੀ ਹੈ। Harris Boat Works ਵਿਖੇ, ਸਾਡਾ 9-ਕਿਸ਼ਤੀਆਂ ਦਾ ਕਿਰਾਏ ਦਾ ਬੇੜਾ ਤੁਹਾਨੂੰ Rice Lake ਦੀ ਸੈਰ ਕਰਨ ਦਾ ਮੌਕਾ ਦਿੰਦਾ ਹੈ, Gores Landing pier ਤੋਂ ਸਿਰਫ਼ ਪਿਕ-ਅੱਪ। ਕਿਰਾਏ ਦੀ ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ ਸੁਰੱਖਿਆ ਬ੍ਰੀਫ਼ਿੰਗ, ਮੁੱਢਲੀ ਚਲਾਉਣ ਦੀਆਂ ਹਦਾਇਤਾਂ, ਸਾਜ਼ੋ-ਸਾਮਾਨ ਦੀ ਜਾਂਚ, ਤੇ ਜਾਂਚ-ਪੱਤਰ ’ਤੇ ਦਸਤਖਤ ਸ਼ਾਮਲ ਹਨ। ਪਹਿਲੀ ਵਾਰ ਕਿਸ਼ਤੀ ਚਾਲਕਾਂ ਲਈ, ਇਹ ਇੰਤਜ਼ਾਮ ਘਬਰਾਹਟ ਘਟਾਉਂਦਾ ਹੈ। ਕਿਰਾਏ ਦੇ ਪੰਨੇ ’ਤੇ ਵੇਰਵਾ ਵੇਖੋ: https://harrisboatworks.ca/rentals

## PCOC online ਕਿਵੇਂ ਬਣਾਈਏ? | How to get PCOC online

Transport Canada ਵੱਲੋਂ ਮਾਨਤਾ ਪ੍ਰਾਪਤ ਨਿੱਜੀ ਕੋਰਸ ਪ੍ਰਦਾਤਾ online ਕੋਰਸ ਪੇਸ਼ ਕਰਦੇ ਹਨ। ਪ੍ਰਕਿਰਿਆ ਸੌਖੀ ਹੈ: online ਪੜ੍ਹਾਈ (ਅਧਿਆਏ, ਵੀਡੀਓ, ਕੁਇਜ਼), ਫਿਰ final Transport Canada exam। ਪਾਸ ਹੋਣ ’ਤੇ ਤੁਹਾਨੂੰ temporary PCOC PDF email ਰਾਹੀਂ ਮਿਲਦੀ ਹੈ; permanent card ਬਾਅਦ ਵਿੱਚ ਡਾਕ ਰਾਹੀਂ। ਕੀਮਤ ਕੋਰਸ ਪ੍ਰਦਾਤਾ ਤੈਅ ਕਰਦੇ ਹਨ, ਅਸੀਂ ਸਹੀ ਡਾਲਰ ਦੀ ਰਕਮ ਨਹੀਂ ਦੱਸ ਸਕਦੇ। ਅਧਿਕਾਰਤ ਪ੍ਰਵਾਨਤ ਪ੍ਰਦਾਤਾਵਾਂ ਦੀ ਸੂਚੀ ਲਈ TC site ’ਤੇ ਜਾਓ: https://tc.canada.ca/en/marine-transportation/buying-boat/find-education-resources-recreational-boaters। exam English ਜਾਂ French ਵਿੱਚ ਹੁੰਦਾ ਹੈ, Punjabi version ਅਧਿਕਾਰਤ ਤੌਰ ’ਤੇ ਮੌਜੂਦ ਨਹੀਂ। free online "Punjabi PCOC" ਦੇ ਦਾਅਵਿਆਂ ’ਤੇ ਭਰੋਸਾ ਨਾ ਕਰੋ, ਸੁਰੱਖਿਅਤ official route ਹੈ, translation app phone ’ਤੇ ਖੋਲ੍ਹ ਕੇ study ਕਰਨਾ possible ਹੈ।

## ਬੱਚੇ ਤੇ supervision: umar ਦੇ rules | Kids and supervision rules

- 16 ਸਾਲ ਤੋਂ ਛੋਟੀ ਉਮਰ ਵਾਲਿਆਂ ਲਈ horsepower ਦੀਆਂ limits ਹਨ, ਜੋ ਉਮਰ ਅਤੇ onboard supervision ’ਤੇ ਨਿਰਭਰ ਕਰਦੀਆਂ ਹਨ।
- ਤਾਜ਼ਾ ਅਤੇ ਪੂਰੇ age-horsepower rules ਸਿਰਫ਼ Transport Canada ਦੇ official ਸਫ਼ੇ ਤੋਂ ਵੇਖੋ: https://tc.canada.ca/en/marine-transportation/preparing-operate-your-vessel/pleasure-craft-operator-card-pcoc
- 16 ਸਾਲ ਤੇ ਇਸ ਤੋਂ ਉੱਤੇ: valid PCOC ਹੋਵੇ ਤਾਂ ਇਕੱਲੇ boat ਚਲਾ ਸਕਦੇ ਹਨ।

Supervisor ਕੋਲ ਜ਼ਰੂਰੀ valid PCOC ਹੋਣੀ ਚਾਹੀਦੀ, boat ’ਤੇ close proximity ਵਿੱਚ। rental checklist option minors ’ਤੇ apply ਨਹੀਂ ਹੁੰਦੀ, young operators ਲਈ PCOC ਜ਼ਰੂਰ ਚਾਹੀਦਾ ਹੈ supervision rules ਨਾਲ। official source ’ਤੇ latest amendments check ਕਰਦੇ ਰਹੋ: https://tc.canada.ca/en/marine-transportation/preparing-operate-your-vessel/pleasure-craft-operator-card-pcoc

## Punjabi community layi ik imandari wali gall | ਪੰਜਾਬੀ ਭਾਈਚਾਰੇ ਲਈ ਇੱਕ ਇਮਾਨਦਾਰੀ ਵਾਲੀ ਗੱਲ

ਅਸੀਂ ਇਹ guide Punjabi ਵਿੱਚ ਇਸ ਲਈ ਬਣਾਈ ਹੈ ਕਿਉਂਕਿ ਅਸੀਂ ਸੱਚਮੁੱਚ ਚਾਹੁੰਦੇ ਹਾਂ ਕਿ Punjabi boaters, ਉਹਨਾਂ ਦੇ ਪਰਿਵਾਰ ਤੇ ਦੋਸਤ Rice Lake ਦਾ ਆਨੰਦ ਲੈ ਸਕਣ। ਇਹ ਕੰਮ ਅਜੇ ਤੱਕ ਬਹੁਤ ਘੱਟ ਲੋਕਾਂ ਨੇ ਕੀਤਾ ਹੈ, ਤੇ ਸਾਨੂੰ ਉਮੀਦ ਹੈ ਕਿ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਜਾਣਕਾਰੀ ਪੜ੍ਹ ਕੇ ਤੁਹਾਡਾ ਡਰ ਥੋੜ੍ਹਾ ਘਟੇਗਾ।

ਇਮਾਨਦਾਰੀ ਦੀ ਗੱਲ: ਸਾਡੀ ਟੀਮ English ਵਿੱਚ ਸੇਵਾ ਦਿੰਦੀ ਹੈ। ਪਰ ਚਿੰਤਾ ਨਾ ਕਰੋ, ਕੋਈ English ਬੋਲਣ ਵਾਲਾ ਦੋਸਤ ਜਾਂ ਪਰਿਵਾਰਕ ਮੈਂਬਰ ਨਾਲ ਲੈ ਆਓ, ਜਾਂ ਆਪਣੇ ਫ਼ੋਨ 'ਤੇ translation app ਵਰਤੋ। ਅਸੀਂ ਸਬਰ ਨਾਲ ਗੱਲ ਕਰਾਂਗੇ ਅਤੇ ਮਿਲ ਕੇ ਹੱਲ ਕੱਢ ਲਵਾਂਗੇ।

## FAQ | ਅਕਸਰ ਪੁੱਛੇ ਜਾਂਦੇ ਸਵਾਲ

**Q: Ontario vich boat chalaun lai license kinj banayiye?**  
A: ਪਹਿਲਾਂ Transport Canada ਦੇ ਮਾਨਤਾ-ਪ੍ਰਾਪਤ ਪ੍ਰਦਾਤਾਵਾਂ ਰਾਹੀਂ online PCOC ਕੋਰਸ ਕਰੋ। exam pass ਕਰੋ, card lifetime ਲਈ ਮਿਲ ਜਾਵੇਗਾ। official list: https://tc.canada.ca/en/marine-transportation/buying-boat/find-education-resources-recreational-boaters

**Q: Je main ik din layi boat rent karan, PCOC deni paini hai?**  
A: ਨਹੀਂ, temporary rental boat safety checklist ’ਤੇ ਦਸਤਖਤ ਕਰਕੇ boat rent ਲੈ ਸਕਦੇ ਹੋ। Harris Boat Works ਦੀ rental fleet ਲਈ ਸਿੱਧਾ https://harrisboatworks.ca/rentals ’ਤੇ ਜਾਓ, full briefing ਮਿਲੇਗੀ।

**Q: Kya “boat license” te “boat operator card” different hunde ne?**  
A: Boat license (PCL) boat ਦੀ registration number ਹੈ; operator card (PCOC) ਤੁਹਾਡੀ training ਦਾ ਸਬੂਤ ਹੈ। ਦੋਵੇਂ ਵਕਤ confuse ਨਾ ਹੋ, official terms PCL ਤੇ PCOC ਯਾਦ ਰੱਖੋ।

**Q: PCOC course online muft Punjabi vich mil sakda ae?**  
A: ਮੁਫ਼ਤ ਦਾ ਨਹੀਂ ਪਤਾ, course providers ਕੀਮਤ ਮੰਗਣਗੇ, ਅਤੇ course English ਜਾਂ French ਵਿੱਚ ਹੀ officially available ਹੈ। Punjabi ਵਿੱਚ approved version Transport Canada ਨਹੀਂ ਰੱਖਿਆ। Phone application translation ਨਾਲ study ਆਸਾਨ ਹੋ ਸਕਦਾ ਹੈ।

**Q: Mere chacha ji apni boat leke Ontario aaye; kya oh bina card de chala sakde?**  
A: ਨਹੀਂ, motor boat operate ਕਰਨ ਲਈ valid PCOC ਹੋਣੀ ਚਾਹੀਦੀ, ਨਹੀਂ ਤਾਂ officer penalty ਲਾ ਸਕਦਾ। Temporary visitor ਵੀ online course ਕੀਤਾ ਜਾ ਸਕਦਾ, ਇਸ ਲਈ planning ਕਰਕੇ ਆਓ।

**Q: Ki Harris Boat Works te Punjabi vich service mildi hai?**  
A: ਇਹ guide Punjabi ਵਿੱਚ ਲਿਖੀ ਸੀ, ਪਰ ਸਾਡੀ ਸੇਵਾ English ਵਿੱਚ ਹੀ ਚੱਲਦੀ ਹੈ। ਨਾਲ English ਦਾ ਬੰਦਾ ਲੈ ਆਓ ਜਾਂ phone translate ਵਰਤੋ, ਅਸੀਂ ਰੁਕ ਕੇ ਸਮਝਾਵਾਂਗੇ, ਕੋਈ ਮੁਸ਼ਕਲ ਨਹੀਂ। (ਉੱਪਰ ਵਾਲੀ ਇਮਾਨਦਾਰੀ ਵਾਲੀ ਗੱਲ ਵੇਖ ਲਓ।)

## Shuru karo apni Rice Lake trip | ਆਪਣੀ ਰਾਈਸ ਲੇਕ ਟ੍ਰਿਪ ਸ਼ੁਰੂ ਕਰੋ

PCOC rules ਨੂੰ ਔਖਾ ਨਾ ਸਮਝੋ; ਪਹਿਲਾ ਕਦਮ safety information ਸਮਝਣਾ ਹੈ। Rice Lake, Gores Landing (5369 Harris Boat Works Rd, Gores Landing, ON K0K 2E0) Toronto area ਤੋਂ 90 minutes ਦੂਰ, Brampton, Mississauga, Scarborough, Markham ਵਾਲਿਆਂ ਲਈ simple day trip ਹੈ। ਸਾਡੀ Ethanol-free fuel site ’ਤੇ ਮਿਲੇਗੀ, ਤੇ Mercury outboard engines 3-year warranty ਨਾਲ confident ਰੱਖਣਗੇ, ਜੇ ਨਵੀਂ boat ਦਾ ਸੋਚ ਰਹੇ ਹੋ। rental booking ਲਈ rent page ਖੋਲ੍ਹੋ: https://harrisboatworks.ca/rentals। service request ਭੇਜਣੀ ਹੈ: hbw.wiki/service। Phone (905) 342-2153, text (647) 952-2153, english ਵਿੱਚ ਜਵਾਬ ਆਵੇਗਾ, ਕਰਕੇ ਦਿਖਾਵਾਂਗੇ, ਦਿਲੋਂ ਸਾਥ ਦਿਆਂਗੇ। December 1 to April 1 ਅਸੀਂ winter break ਵਿੱਚ ਬੰਦ ਰਹਿੰਦੇ ਹਾਂ, oh season Rice Lake ’ਤੇ ਨਹੀਂ ਚੱਲਦਾ।`
  },
  {
    slug: 'mercury-outboard-prices-ontario-punjabi',
    title: 'Mercury outboard motor di keemat Canada vich | ਮਰਕਰੀ ਆਊਟਬੋਰਡ ਕੀਮਤ ਗਾਈਡ Ontario',
    seoTitle: 'Mercury outboard motor di keemat Canada vich | ਮਰਕਰੀ ਆਊਟਬੋਰਡ ਕੀਮਤ ਗਾਈਡ Ontario',
    description: 'Mercury outboard motor di keemat Canada vich: HP class anusar price structure, repower cost te live quote tool. Punjabi guide, koi lukiyan hoiyan fees nahi.',
    image: '/lovable-uploads/hero-cheapest-mercury-canada-lineup.png',
    author: 'Harris Boat Works',
    datePublished: '2026-06-12',
    dateModified: '2026-07-10',
    category: 'ਪੰਜਾਬੀ ਗਾਈਡ',
    readTime: '8 ਮਿੰਟ',
    keywords: ['Mercury outboard motor di keemat Canada vich (Mercury outboard motor price in Canada)', 'Mercury 90hp outboard price Ontario Punjabi (Mercury 90hp outboard price Ontario Punjabi)', 'outboard motor dealer near Toronto Punjabi speaking (outboard motor dealer near Toronto who speaks Punjabi)', 'new outboard motor khareedan di guide Punjabi (guide to buying a new outboard motor in Punjabi)', 'Mercury vs Yamaha outboard video Punjabi (Mercury vs Yamaha outboard video in Punjabi)'],
    faqs: [
      { question: 'Mercury 90hp outboard di Ontario vich keemat kitni hai? | ਮਰਕਰੀ 90hp ਆਊਟਬੋਰਡ ਦੀ Ontario ਵਿਚ ਕੀਮਤ ਕਿੰਨੀ ਹੈ?', answer: 'ਕੋਈ ਇੱਕ number ਨਹੀਂ। ਹਰ boat ਲਈ installed price ਵੱਖਰੀ ਹੋਵੇਗੀ। Rigging, propeller, labour ਨਾਲ ਜੋੜ ਕੇ ਹੀ ਅਸਲ cost ਨਿਕਲਦੀ ਹੈ। ਤੁਸੀਂ ਸਾਡੇ pricing reference page (https://www.mercuryrepower.ca/pricing-reference) ’ਤੇ ਮਿਸਾਲ ਦੇ component ਦੇਖ ਸਕਦੇ ਹੋ। ਫੇਰ quote ਲਈ phone ਕਰੋ, ਅਸੀਂ ਤੁਹਾਡੀ specific boat ਲਈ ਬਣ ਕੇ ਦੱਸਾਂਗੇ।' },
      { question: 'Ki Harris Boat Works te Punjabi vich service mildi hai? | ਕੀ Harris Boat Works ’ਤੇ ਪੰਜਾਬੀ ਵਿੱਚ service ਮਿਲਦੀ ਹੈ?', answer: 'ਸਾਡੇ ਕੋਲ Punjabi ਬੋਲਣ ਵਾਲਾ ਕੋਈ staff ਨਹੀਂ ਹੈ। Harris Boat Works ਦੀ team English ਵਿੱਚ ਸੇਵਾ ਦਿੰਦੀ ਹੈ। ਪਰ ਤੁਸੀਂ ਆਪਣੇ ਨਾਲ ਕੋਈ English ਜਾਣਦਾ ਸਾਥੀ ਲੈ ਆ ਸਕਦੇ ਹੋ, ਜਾਂ phone ’ਤੇ translate app ਵਰਤੋ। ਸਾਡੇ ਕੋਲ ਬਹੁਤ ਲੋਕ ਇਸ ਤਰ੍ਹਾਂ ਆਉਂਦੇ ਨੇ, ਤੇ ਕੰਮ ਆਰਾਮ ਨਾਲ ਹੋ ਜਾਂਦਾ ਹੈ। ਕੋਈ ਪਰੇਸ਼ਾਨੀ ਨਹੀਂ ਹੋਵੇਗੀ।' },
      { question: 'Nawa outboard motor khareedan layi kuch tips deyo Punjabi vich? | ਨਵਾਂ ਆਊਟਬੋਰਡ ਮੋਟਰ ਖਰੀਦਣ ਲਈ ਕੁਝ ਟਿਪਸ ਦਿਓ ਪੰਜਾਬੀ ਵਿਚ?', answer: 'ਜ਼ਰੂਰ। (1) ਹਮੇਸ਼ਾ installed quote ਮਨਜ਼ੂਰ ਕਰੋ, ਸਿਰਫ਼ motor ਦਾ ਮੁੱਲ ਪੁੱਛ ਕੇ ਨਾ ਰੁਕੋ। (2) Boat ਦੀ horsepower rating plate ਵੇਖ ਕੇ ਆਪਣਾ HP range ਚੁਣੋ। (3) Mercury ਦੀ 3-year warranty ਬਾਰੇ ਪੁੱਛੋ, ਅਤੇ authorized installation ਦਾ proof ਰੱਖੋ। (4) ਨਵਾਂ control box, propeller, ਅਤੇ wiring update ਕਰਨ ਲਈ ready ਰਹੋ, ਜੇ ਪੁਰਾਣੀ motor 15 ਸਾਲ ਤੋਂ ਵੱਧ ਹੈ। (5) Financing ਦੀ ਪੂਰੀ ਜਾਣਕਾਰੀ ਸਾਡੀ [English financing guide](https://www.mercuryrepower.ca/blog/mercury-outboard-financing-ontario-2026) ਵਿੱਚ ਹੈ।' },
      { question: 'Ki tuhade kolo Mercury di doosre brand naal tulna de Punjabi vich video ne? | ਕੀ ਤੁਹਾਡੇ ਕੋਲੋਂ Mercury ਦੀ ਦੂਜੇ brand ਨਾਲ ਤੁਲਨਾ ਦੇ ਪੰਜਾਬੀ ਵਿਚ ਵੀਡੀਓ ਨੇ?', answer: 'ਨਹੀਂ ਜੀ, ਸਾਡੇ ਕੋਲ ਕਿਸੇ brand ਦੇ comparison video ਨਹੀਂ ਨੇ। ਪਰ ਸਾਨੂੰ Mercury ਦੇ features ਬਾਰੇ ਜਾਣਨਾ ਹੈ ਤਾਂ ਸਮਝਾ ਸਕਦੇ ਹਾਂ। ਤੁਸੀਂ ਆਪਣੇ ਲਈ ਸਹੀ motor ਦਾ ਫੈਸਲਾ ਖੁਦ ਕਰ ਸਕਦੇ ਹੋ, ਸਾਡੇ quote tool ਦੇ suggest ਅਨੁਸਾਰ। Video ਵੇਖਣੀ ਹੈ ਤਾਂ YouTube ’ਤੇ general “outboard comparison” search ਕਰੋ, ਪਰ ਯਾਦ ਰੱਖੋ, ਲੋਕ ਆਪਣਾ personal opinion ਦਿੰਦੇ ਨੇ, test data ਨਹੀਂ।' },
      { question: 'Main bina dealer nu mile motor da quote labh sakda haan? | ਮੈਂ ਬਿਨਾਂ ਡੀਲਰ ਨੂੰ ਮਿਲੇ ਮੋਟਰ ਦਾ quote ਲੱਭ ਸਕਦਾ ਹਾਂ?', answer: 'ਜੀ ਹਾਂ, ਸਾਡੇ motor selection tool (https://www.mercuryrepower.ca/quote/motor-selection) ’ਤੇ boat details ਪਾ ਕੇ, ਤੁਹਾਨੂੰ ਕੁਝ Mercury model ਦਿਖਾਏ ਜਾਣਗੇ। ਬਾਅਦ ਵਿੱਚ ਸਾਨੂੰ call ਕਰੋ ਤਾਂ installed quote ਦੇ ਸਕਦੇ ਹਾਂ। ਇਹਦੇ ਵਿੱਚ ਕੋਈ loading ਜਾਂ pressure ਨਹੀਂ।' },
      { question: 'Main apni old motor nu trade-in de sakda haan? | ਮੈਂ ਆਪਣੀ ਪੁਰਾਣੀ ਮੋਟਰ ਨੂੰ trade-in ਦੇ ਸਕਦਾ ਹਾਂ?', answer: 'ਕੁਝ ਹਾਲਤਾਂ ਵਿੱਚ ਹੋ ਸਕਦਾ ਹੈ, ਪਰ ਅਸੀਂ ਹਰ ਪੁਰਾਣੀ motor ਨਹੀਂ ਲੈ ਸਕਦੇ। ਪਹਿਲਾਂ photo ਭੇਜ ਕੇ ਪੁੱਛੋ। ਦੂਜੀ ਗੱਲ: trade value installed price ਵਿੱਚ adjust ਕੀਤੀ ਜਾ ਸਕਦੀ ਹੈ, ਜੇ motor ਦੀ condition ਚੰਗੀ ਹੋਵੇ। Phone ’ਤੇ ਇਸ ਲਈ ਸਾਨੂੰ English ਵਿੱਚ ਗੱਲ ਕਰਨੀ ਹੋਵੇਗੀ, ਉੱਤੇ ਦੱਸੇ ਅਨੁਸਾਰ ਦੋਸਤ ਨਾਲ ਆਓ ਜਾਂ translation app use ਕਰੋ।' },
      { question: 'Harris Boat Works da pata ki hai? | Harris Boat Works ਦਾ ਪਤਾ ਕੀ ਹੈ?', answer: 'ਸਾਡਾ address 5369 Harris Boat Works Rd, Gores Landing, ON K0K 2E0 ਹੈ। Brampton, Mississauga, Scarborough, Markham ਤੋਂ ਗੱਡੀ ਰਾਹੀਂ ਤਕਰੀਬਨ 90-minute ਲੱਗਦੇ ਨੇ। ਅਸੀਂ 1 December to 1 April ਤੱਕ ਬੰਦ ਰਹਿੰਦੇ ਹਾਂ। Season ਵਿੱਚ ਸਾਨੂੰ phone (905) 342-2153 ਜਾਂ text (647) 952-2153 ਕਰੋ। Service request direct hbw.wiki/service ’ਤੇ ਜਮ੍ਹਾ ਕਰ ਸਕਦੇ ਹੋ।' }
    ],
    nativeReview: 'pending',
    internalLinks: ['https://www.mercuryrepower.ca/quote/motor-selection', 'https://www.mercuryrepower.ca/pricing-reference', 'https://www.mercuryrepower.ca/blog/mercury-outboard-financing-ontario-2026'],
    officialSources: [],
    content: `ਸਿੱਧੀ ਗੱਲ: Mercury outboard ਦੀ ਕੋਈ ਇੱਕ fixed ਕੀਮਤ ਨਹੀਂ ਹੁੰਦੀ; ਅਸਲ installed cost motor, rigging, propeller, labour ਅਤੇ ਤੁਹਾਡੀ boat ਦੇ setup ’ਤੇ ਨਿਰਭਰ ਕਰਦਾ ਹੈ। ਤਾਜ਼ਾ, transparent ਕੀਮਤ ਲਈ ਸਾਡਾ quote configurator ਵਰਤੋ: https://www.mercuryrepower.ca/quote/motor-selection। Harris Boat Works ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ। ਅਸੀਂ 1965 ਤੋਂ Mercury dealer ਹਾਂ, ਹੁਣ Premier dealer, ਅਤੇ ਸਮਝਣ ਵਾਲੇ ਲੋਕ ਜਾਣਦੇ ਨੇ ਕਿ Brampton, Mississauga, Markham ਵਿੱਚੋਂ family ਆਪਣੀ boat ਲਈ outboard ਦੀ ਕੀਮਤ ਪੁੱਛਦੇ ਆ। ਇਹ guide Punjabi Gurmukhi ਵਿੱਚ ਲਿਖੀ ਗਈ ਹੈ ਤਾਂਕਿ ਤੁਸੀਂ ਖਰੀਦ ਤੋਂ ਪਹਿਲਾਂ ਸਹੀ budget ਬਣਾ ਸਕੋ। ਇੱਕ ਗੱਲ ਪੱਕੀ: internet ਤੇ ਕਿਸੇ ਵੀ outboard ਦੀ ਇੱਕ fixed ਕੀਮਤ ਨਹੀਂ ਮਿਲਦੀ, ਪਰ ਅਸਲ ਹਿਸਾਬ-ਕਿਤਾਬ ਸਮਝ ਕੇ ਤੁਸੀਂ ਬੇਫ਼ਿਕਰ deal ਕਰ ਸਕਦੇ ਹੋ। ਅਸੀਂ ਤੁਹਾਨੂੰ ਦੱਸਦੇ ਹਾਂ ਕਿ ਕੀਮਤ ਕਿੰਜ ਬਣਦੀ ਹੈ, ਕਿਹੜੀਆਂ-ਕਿਹੜੀਆਂ ਚੀਜ਼ਾਂ ਖਰਚ ਵਧਾਉਂਦੀਆਂ ਨੇ, ਅਤੇ Mercury ਦੀ ਲੈਣ ਤੋਂ ਬਾਅਦ ਕਿੰਜ ਮਨ ਦੀ ਸ਼ਾਂਤੀ ਰਹੇਗੀ। ਕੋਈ dollar amount ਅਸੀਂ ਨਹੀਂ ਲਿਖ ਸਕਦੇ, ਕਿਉਂਕਿ ਹਰੇਕ ਕਿਸ਼ਤੀ ਅਤੇ ਹਰੇਕ setup ਆਪਣਾ ਖਰਚ ਰੱਖਦਾ ਹੈ। ਪਰ ਥੋਨੂੰ ਇੱਕ ਸਹੀ ਰਾਹ ਜ਼ਰੂਰ ਦਿਖਾਵਾਂਗੇ।

## Outboard motor di asal keemat: sirf motor hi nahi | ਆਊਟਬੋਰਡ ਮੋਟਰ ਦੀ ਅਸਲ ਕੀਮਤ: ਸਿਰਫ਼ ਮੋਟਰ ਹੀ ਨਹੀਂ

ਜਦੋਂ ਤੁਸੀਂ “Mercury 90hp price” ਲੱਭਦੇ ਹੋ, ਤੁਹਾਡੀ screen ’ਤੇ ਆਸਾਨੀ ਨਾਲ ਕੋਈ number ਨਹੀਂ ਆਉਂਦਾ। ਇਸ ਦਾ ਕਾਰਨ ਹੈ ਕਿ motor ਦੀ factory price ਸਿਰਫ਼ ਇੱਕ ਤੁੱਕਾ ਹੈ। ਪੂਰੇ installed system ਦਾ ਖਰਚ ਉਹ ਮੋਟਰ, rigging kit (throttle ਤੇ shift cables, key switch, wiring harness), controls (side-mount ਜਾਂ binnacle), propeller, ਅਤੇ labour ਨੂੰ ਜੋੜ ਕੇ ਬਣਦਾ ਹੈ। ਇਹ ਸਭ ਕੁਝ ਤੁਹਾਡੀ boat model, transom ਦੀ height (15″, 20″, 25″), ਅਤੇ ਕਿਸ਼ਤੀ ਵਿੱਚ ਪਹਿਲਾਂ ਤੋਂ ਕਿੰਨਾ ਕੁਝ ਮੌਜੂਦ ਹੈ, ਉੱਤੇ depend ਕਰਦਾ ਹੈ। ਬਿਨਾਂ ਸਹੀ rigging ਦੇ motor ਚੱਲੇਗੀ ਨਹੀਂ, ਅਤੇ ਬਿਨਾਂ prop ਦੇ ਪਾਣੀ ਵਿੱਚ ਕੋਈ ਜ਼ੋਰ ਨਹੀਂ। ਇਸ ਲਈ ਹਰ dealer “turn-key” installed quote ਦੇਣ ਦਾ ਆਦੀ ਹੈ। ਜੇ ਤੁਸੀਂ ਸਿਰਫ਼ motor ਦੀ MRP ਪੁੱਛੋਗੇ, ਉਹ ਅਧੂਰੀ ਤਸਵੀਰ ਹੋਵੇਗੀ। ਇਹ ਗੱਲ ਤੁਹਾਨੂੰ ਪੈਸੇ ਬਚਾਉਂਦੀ ਤੇ ਧੋਖਾ ਹੋਣ ਤੋਂ ਰੋਕਦੀ ਹੈ। ਸਾਨੂੰ phone ਕਰੋ ਜਾਂ ਸਾਡੇ quote tool ਨੂੰ ਵਰਤ ਕੇ ਸਮਝੋ ਕਿ ਅਸਲ ਵਿੱਚ ਤੁਹਾਡੀ boat ਵਿੱਚ ਕਿੰਨੀ motor fit ਆਉਣੀ ਹੈ। ਸਾਡੇ pricing reference page ’ਤੇ ਜਾਣ ਨਾਲ ਤੁਸੀਂ example cost structures ਦੇਖ ਸਕਦੇ ਹੋ (ਕੋਈ dollar figure ਉੱਥੇ ਨਹੀਂ, ਪਰ ਹਿੱਸੇ ਦਾ idea ਮਿਲੇਗਾ)। ਇਹ page ਹਰ motor ਲਈ general ਮਿਸਾਲਾਂ ਦਿਖਾਉਂਦਾ ਹੈ, ਜਿਸ ਨਾਲ ਤੁਹਾਨੂੰ ਸਮਝ ਆਉਣੀ ਅਸਾਨ ਹੋਵੇਗੀ। ਯਾਦ ਰੱਖੋ: ਜੇ ਕੋਈ dealer ਸਿਰਫ਼ motor ਦਾ rate ਦੱਸ ਕੇ ਗੱਲ ਬੰਦ ਕਰਦਾ ਹੈ, ਉਹ ਤੁਹਾਡੀ safe boating ਦੀ ਪੂਰੀ ਜ਼ਿੰਮੇਵਾਰੀ ਨਹੀਂ ਲੈ ਰਿਹਾ।

## HP da chon, tuhadi kishti layi sahi taqat | HP ਦਾ ਚੋਣ, ਤੁਹਾਡੀ ਕਿਸ਼ਤੀ ਲਈ ਸਹੀ ਤਾਕਤ

Mercury outboard ਬਹੁਤ ਸਾਰੇ horsepower (HP) ranges ਵਿੱਚ ਆਉਂਦੇ ਨੇ, ਛੋਟੀਆਂ portables ਤੋਂ ਲੈ ਕੇ ਵੱਡੀਆਂ high-performance motors ਤੱਕ। ਪਰ ਆਮ GTA family ਲਈ, Rice Lake ਜਾਣ ਵਾਸਤੇ, ਕੁਝ popular options ਨੇ:

* **ਛੋਟੀਆਂ fishing boats (12-14 ft), tin boats, ਜਾਂ tenders:** 6 HP ਤੋਂ 20 HP। ਇੰਜ ਬਿਨਾਂ ਜ਼ਿਆਦਾ ਭਾਰ ਦੇ fish ਕਰਦਾ ਆਰਾਮ ਨਾਲ ਸਵੇਰਾ ਕੀਤਾ ਜਾ ਸਕਦਾ ਹੈ। Portability ਵੀ ਚੰਗੀ ਹੈ।
* **Family fishing/recreational (16-18 ft aluminum ਜਾਂ fiberglass):** 40 HP ਤੋਂ 115 HP। ਇਹ range ਸਾਡੇ top sellers ਵਿੱਚੋਂ ਹੈ। Mercury 90hp ਇੱਕ ਬਹੁਤ ਭਰੋਸੇਮੰਦ motor ਹੈ ਜੋ 16-18 ft boats ਲਈ ਆਮ ਤੌਰ ’ਤੇ ਢੁਕਵੀਂ ਰਹਿੰਦੀ ਹੈ; ਅਸਲ performance boat, load ਅਤੇ propeller ’ਤੇ ਨਿਰਭਰ ਕਰਦੀ ਹੈ। ਇਸ ਲਈ ਅਕਸਰ Brampton ਵਾਲੇ “Mercury 90hp outboard price Ontario” ਪੁੱਛਦੇ ਨੇ, ਪਰ ਯਾਦ ਰੱਖੋ, ਸਿਰਫ਼ motor ਨਹੀਂ, ਪੂਰੀ installed ਕੀਮਤ ਪੁੱਛਣੀ ਹੈ। 115 HP ਮਿਲਦੀ ਹੈ ਉਨ੍ਹਾਂ ਲਈ ਜਿਹੜੇ full family ਪਾਣੀ ਦੇ toys ਨਾਲ ਨਿਕਲਣਾ ਚਾਹੁੰਦੇ ਨੇ।
* **Pontoon boats ਜਾਂ ਭਾਰੀ ਕਿਸ਼ਤੀਆਂ:** 150 HP and up। ਚੰਗੀ planning ਤੇ pulling power ਲਈ।
* **Bass boats ਜਾਂ performance ਵਾਲਿਆਂ ਲਈ:** 200 HP ਤੋਂ 300 Pro XS series।

ਜੇ ਤੁਹਾਨੂੰ ਪਤਾ ਨਹੀਂ ਕਿ ਤੁਹਾਡੀ ਕਿਸ਼ਤੀ ਕਿੰਨੀ HP ਝੱਲ ਸਕਦੀ ਹੈ, boat ਦੀ maximum rating plate (transom ਦੇ ਕੋਲ) ਵੇਖੋ। ਉਹਦੀ ਹੱਦ ਤੋਂ ਵੱਧ motor ਲਗਾਉਣੀ illegal ਅਤੇ danger ਹੈ। ਅਸੀਂ ਦੇਖ ਕੇ ਦੱਸ ਸਕਦੇ ਹਾਂ ਕਿ Mercury ਦਾ ਕਿਹੜਾ model fit ਹੋਵੇਗਾ। ਜੇ motor ਦੀ ਚੋਣ ਦਾ matter ਹੈ, ਸਾਡੇ online quote tool (Motor Selection) ’ਤੇ ਜਾ ਕੇ boat ਦਾ year, make, ਅਤੇ ਆਮ load ਚੁਣੋ, ਤੇ ਉਹ ਤੁਹਾਨੂੰ suggest ਕਰੇਗਾ। ਬਾਅਦ ਵਿੱਚ ਅਸੀਂ phone ’ਤੇ estimate ਦੇਵਾਂਗੇ।

## Purani motor badalni hai? Repower di salah | ਪੁਰਾਣੀ ਮੋਟਰ ਬਦਲਣੀ ਹੈ? ਰੀਪਾਵਰ ਦੀ ਸਲਾਹ

ਬਹੁਤ ਲੋਕ ਆਪਣੀ ਪੁਰਾਣੀ boat ਨੂੰ ਪਿਆਰ ਕਰਦੇ ਨੇ, ਪਰ motor ਨੇ ਸਾਥ ਛੱਡ ਦਿੱਤਾ। “Repower” ਦਾ ਮਤਲਬ ਹੈ ਕਿ ਨਵਾਂ outboard ਲਗਾਓ, ਚਾਹੇ Mercury ਹੀ ਹੋਵੇ, ਕਿਸੇ ਹੋਰ brand ਦਾ replace ਕਰਨਾ। Repower ਵਿੱਚ ਖਰਚ ਬੱਸ motor ’ਤੇ ਹੀ ਨਹੀਂ, ਬਲਕਿ ਪੁਰਾਣੇ controls, wiring, ਅਤੇ fuel system ਨੂੰ update ਕਰਨ ਵਿੱਚ ਵੀ ਲੱਗਦਾ ਹੈ, ਖ਼ਾਸ ਕਰਕੇ ਜੇ 2-stroke ਤੋਂ 4-stroke ’ਤੇ ਆ ਰਹੇ ਹੋ। ਸਾਡੇ mechanics GPS speedometer integration ਤੱਕ ਦਾ ਖਿਆਲ ਰੱਖਦੇ ਨੇ, ਅਤੇ ethanol-free fuel ਸਾਡੇ dock ’ਤੇ ਮਿਲਦੀ ਹੈ, ਜੋ ਨਵੀਂ motor ਦੀ life ਵਧਾਉਂਦੀ ਹੈ। Repower ਲਈ ਪਹਿਲੀ ਸਲਾਹ: ਅਸੀਂ ਕਦੇ phone ’ਤੇ ਅੱਖ ਬੰਦ ਕਰਕੇ quote ਨਹੀਂ ਦਿੰਦੇ। ਸਾਡੇ ਤੋਂ quote ਲੈਣ ਤੋਂ ਪਹਿਲਾਂ ਤੁਸੀਂ boat ਦੀਆਂ ਕੁਝ ਨਿਆਮਤਾਂ photos whatsapp ’ਤੇ ਭੇਜੋ: transom bracket, current controls, ਅਤੇ motor model number। ਫਿਰ ਅਸੀਂ ਤੁਹਾਨੂੰ ਲੱਭ ਕੇ ਦੱਸਾਂਗੇ ਕਿ ਤੁਹਾਡੇ setup ਲਈ ਕਿੰਨਾ ਖਰਚ ਆਵੇਗਾ। ਜੇ ਤੁਸੀਂ ਆਪਣੀ ਪੁਰਾਣੀ motor ਵੇਚ ਕੇ ਆਉਣਾ ਚਾਹੁੰਦੇ ਹੋ, ਉਹ ਗੱਲ ਵੀ ਕਰੋ। ਸਾਡਾ contact number (905) 342-2153 ਜਾਂ text (647) 952-2153 ਹੈ।

## Mercury warranty: man di shanti | Mercury ਵਾਰੰਟੀ: ਮਨ ਦੀ ਸ਼ਾਂਤੀ

ਹਰ ਨਵੀਂ Mercury outboard ’ਤੇ factory 3-year base warranty ਆਉਂਦੀ ਹੈ। ਇਸ ਦਾ ਮਤਲਬ, ਜੇ ਕੋਈ material ਜਾਂ workmanship ਦਾ fault ਹੋਇਆ, Mercury ਉਸਨੂੰ cover ਕਰਦੀ ਹੈ, ਚਾਹੇ ਤੁਸੀਂ ਕਿਸੇ ਵੀ authorized dealer ਤੋਂ ਲਓ। Premier dealer ਹੋਣ ਦਾ ਫਾਇਦਾ ਇਹ ਹੈ ਕਿ ਸਾਡੇ technicians ਹਰ training ਦੀ training ਪਾਸ ਕਰ ਚੁੱਕੇ ਨੇ, service genuine parts ਨਾਲ ਕਰਦੇ ਨੇ, ਅਤੇ warranty ਦਾ claim ਆਸਾਨੀ ਨਾਲ ਸਾਨੂੰ ਹੀ ਕਰਨਾ ਪੈਂਦਾ ਹੈ, ਤੁਹਾਨੂੰ ਸਿਰਫ਼ motor ਚਲਾਉਣੀ ਹੈ। ਕੁਝ ਲੋਕ extended warranty ਬਾਰੇ ਵੀ ਪੁੱਛਦੇ ਨੇ; ਤਾਜ਼ਾ options ਲਈ ਸਾਨੂੰ ਪੁੱਛ ਲਓ। ਉਹ ਬਾਰੇ ਵਿਚਾਰ ਕਰੋ ਜੇ ਤੁਸੀਂ ਬਹੁਤ ਘੰਟੇ ਪਾਣੀ ’ਤੇ ਹੁੰਦੇ ਹੋ। ਇੱਕ ਪੱਕੀ ਗੱਲ: warranty ਦੀ ਸ਼ਰਤ ਸਿਰਫ authorized installation ਅਤੇ scheduled service ਨਾਲ ਹੀ ਪੂਰੀ ਹੁੰਦੀ ਹੈ। ਸਾਨੂੰ ਇਹ free ਵਿੱਚ guide ਕਰਕੇ ਦੱਸਾਂਗੇ ਕਿ ਤੁਹਾਡੀ motor ਦੀ warranty ਕਦੋਂ ਤੱਕ ਅਤੇ ਕਿਵੇਂ valid ਰੱਖਣੀ ਹੈ।

## Ik sahi quote kiven laini hai | ਇੱਕ ਸਹੀ ਕੋਟ ਕਿਵੇਂ ਲੈਣੀ ਹੈ

Outboard ਖਰੀਦ ਦਾ ਕਦਮ ਫੂਕ-ਫੂਕ ਕੇ ਰੱਖਣਾ ਚੰਗਾ ਹੈ। ਸਾਡੀ ਸਲਾਹ ਹੈ:

1. **Online ਸ਼ੁਰੂ ਕਰੋ:** ਸਾਡੇ Mercury Repower page (https://www.mercuryrepower.ca/quote/motor-selection) ’ਤੇ ਆਪਣੀ boat ਦੀ ਮਾਲੂਮਾਤ ਭਰੋ, boat brand, length, haul load, preferred activity। ਇਹ tool ਤੁਹਾਨੂੰ suggested Mercury models ਦਿਖਾਏਗਾ। ਕੋਈ price ਨਹੀਂ, ਪਰ ਤਕਰੀਬਨ range ਪਤਾ ਲੱਗੂ।
2. **ਸਾਨੂੰ phone ਕਰਕੇ follow-up ਕਰੋ:** (905) 342-2153. Markham, Scarborough, Mississauga, Brampton, ਅਸੀਂ 90-minute drive ਦੂਰ ਹਾਂ, ਪਰ quote ਲੈਣਾ free ਹੈ। ਦੱਸਿਓ ਕਿ ਤੁਸੀਂ Punjabi guide ਪੜ੍ਹ ਕੇ call ਕੀਤਾ ਹੈ, ਅਸੀਂ ਥੋਨੂੰ ਆਰਾਮ ਨਾਲ ਸਮਝਾਵਾਂਗੇ। ਜੇ ਤੁਹਾਨੂੰ English ਚ ਬੋਲਣ ਵਾਲਾ ਦੋਸਤ ਨਾਲ ਲਿਆਉਣਾ ਪੈ ਸਕਦਾ ਹੈ (ਥੱਲ੍ਹੇ ਇਸਦਾ ਜ਼ਿਕਰ ਹੈ), ਤਾਂ ਅਸੀਂ ਆਰਾਮ ਨਾਲ phone ’ਤੇ ਵੀ ਗੱਲ ਕਰ ਸਕਦੇ ਹਾਂ।
3. **Installed quote ਦੇ estimate ਵਿੱਚ ਇਹ ਗੱਲਾਂ ਸ਼ਾਮਲ ਹੋਣੀਆਂ ਚਾਹੀਦੀਆਂ:** motor, controls, prop, rigging harness, labour, batteries, gauges (ਜੇ ਲੋੜ ਪਵੇ), ਅਤੇ ਜੋ ਵੀ ਪੁਰਾਣੀ ਚੀਜ਼ change ਹੋਣੀ ਹੈ। ਆਖਰੀ ਗਿਣਤੀ dollar ਵਿੱਚ ਅਸੀਂ ਤੁਰੰਤ ਨਹੀਂ ਦੇ ਸਕਦੇ ਪਰ ਸਾਡੇ pricing reference page ਨੂੰ ਵੇਖ ਕੇ ਤੁਸੀਂ ਮਿਸਾਲ ਦੇ budget columns ਸਮਝ ਸਕਦੇ ਹੋ। ਉਹ page https://www.mercuryrepower.ca/pricing-reference ’ਤੇ ਹੈ।
4. **Dealership ’ਤੇ ਆਓ ਜੇ ਹੋ ਸਕੇ:** ਜੇ ਤੁਸੀਂ physically ਆਉਣਾ ਚਾਹੁੰਦੇ ਹੋ, Gores Landing ਦਾ address 5369 Harris Boat Works Rd, Gores Landing, ON K0K 2E0 ਹੈ। ਯਾਦ ਰੱਖੋ ਅਸੀਂ 1 December ਤੋਂ 1 April ਤੱਕ winter closed ਹਾਂ। ਬਾਕੀ ਮੌਸਮ ਵਿੱਚ ਆ ਕੇ ਸਾਡੇ set up ਦੇਖ ਸਕਦੇ ਹੋ।

## Imaandaari di gal: eh guide Punjabi vich kyon hai? | ਇਮਾਨਦਾਰੀ ਦੀ ਗੱਲ: ਇਹ ਗਾਈਡ ਪੰਜਾਬੀ ਵਿਚ ਕਿਉਂ ਹੈ?

ਤੁਸੀਂ Punjabi Gurmukhi ਵਿੱਚ ਲਿਖੀ ਇਹ guide ਹਾਲੇ ਪੜ੍ਹ ਰਹੇ ਹੋ। ਸਾਨੂੰ ਬਹੁਤ ਚੰਗਾ ਲੱਗਾ। ਇਹ ਅਸੀਂ ਇਸ ਲਈ ਬਣਾਈ ਕਿਉਂਕਿ GTA ਦੀ Punjabi community ਦੇ ਬਹੁਤ ਲੋਕੀਂ ਪਹਿਲੀ ਵਾਰ boating ਕਰਦੇ ਨੇ, ਤੇ Canada ਵਿੱਚ motor ਖਰੀਦਣ ਦੇ ਢੰਗ ਬਾਰੇ Punjabi ਵਿੱਚ ਜਾਣਕਾਰੀ ਮਿਲਣੀ ਬਹੁਤ ਮੁਸ਼ਕਿਲ ਹੈ। ਇਹ marina 1947 ਤੋਂ Rice Lake ’ਤੇ ਸਾਡੇ ਪਰਿਵਾਰ ਕੋਲ ਹੈ, ਪਰ ਅੱਜ ਤੱਕ ਕਦੇ ਕਿਸੇ ਨੇ Punjabi ਵਿੱਚ ਸਮਝ ਨਹੀਂ ਦਿੱਤੀ। ਸਾਨੂੰ ਲੱਗਾ, ਇਹ ਤੁਹਾਡੇ ਲਈ ਹੱਕ ਹੈ। ਇਸ guide ਵਿੱਚ ਅਸੀਂ ਤੁਹਾਡੀ ਭਾਵਨਾ ਨੂੰ ਸੱਚੇ ਦਿਲ ਨਾਲ ਸਮਝਿਆ ਹੈ।

Honestly, ਸਾਨੂੰ Punjabi ਵਿੱਚ ਗੱਲ ਕਰਨੀ ਨਹੀਂ ਆਉਂਦੀ। Harris Boat Works ਦੀ team English ਵਿੱਚ ਸੇਵਾ ਦਿੰਦੀ ਹੈ, parts counter, service desk, motor ਵੇਚਣ ਵਾਲਾ ਬੰਦਾ, ਸਭ English। ਕੋਈ ਅਜਿਹਾ staff member ਨਹੀਂ ਜੋ Punjabi ਬੋਲ ਸਕਦਾ। ਚਿੰਤਾ ਨਾ ਕਰੋ। ਸਾਡੀ team ਦਹਾਕਿਆਂ ਤੋਂ boat families ਦੀ ਮਦਦ ਕਰਦੀ ਆ ਰਹੀ ਹੈ, ਭਾਸ਼ਾ ਰੁਕਾਵਟ ਨਹੀਂ ਹੈ। ਜੇ ਤੁਹਾਨੂੰ ਲੱਗਦਾ ਹੈ ਕਿ ਭਾਸ਼ਾ ਦਾ ਪੜਦਾ ਹੋ ਸਕਦਾ ਹੈ, ਆਪਣੇ ਨਾਲ ਕੋਈ English ਜਾਣਦਾ ਦੋਸਤ, ਭਰਾ, ਭੈਣ, ਜਾਂ ਬੱਚਾ ਜ਼ਰੂਰ ਲੈ ਆਇਓ। ਨਹੀਂ ਤਾਂ ਆਪਣੇ smartphone ’ਤੇ Google Translate app ਖੋਲ੍ਹੋ, ਉਹਦੇ ਵਿੱਚ camera ਤੇ text translation ਦੋਵੇਂ ਹੁੰਦੇ ਨੇ। ਅਸੀਂ ਹੌਲੀ-ਹੌਲੀ ਬੋਲਾਂਗੇ, ਕੰਮ simple ਕਰਾਂਗੇ, ਤੇ ਲੋੜ ਪਈ ਤਾਂ ਲਿਖ ਕੇ ਸਮਝਾਵਾਂਗੇ। ਇੱਥੋਂ ਦੀ ਹਰ ਗੱਲ ਸਾਂਝੀ ਸਮਝ ਨਾਲ ਹੀ ਸੁਲਝੇਗੀ। ਤੁਸੀਂ welcome ਹੋ, ਚਾਹੇ ਕੋਈ ਵੀ ਭਾਸ਼ਾ ਬੋਲਦਾ ਹੋਵੇ।

## Aksar puchhe jaande sawaal | ਅਕਸਰ ਪੁੱਛੇ ਜਾਂਦੇ ਸਵਾਲ

**Q: Mercury 90hp outboard di Ontario vich keemat kitni hai? | ਮਰਕਰੀ 90hp ਆਊਟਬੋਰਡ ਦੀ Ontario ਵਿਚ ਕੀਮਤ ਕਿੰਨੀ ਹੈ?**
A: ਕੋਈ ਇੱਕ number ਨਹੀਂ। ਹਰ boat ਲਈ installed price ਵੱਖਰੀ ਹੋਵੇਗੀ। Rigging, propeller, labour ਨਾਲ ਜੋੜ ਕੇ ਹੀ ਅਸਲ cost ਨਿਕਲਦੀ ਹੈ। ਤੁਸੀਂ ਸਾਡੇ pricing reference page (https://www.mercuryrepower.ca/pricing-reference) ’ਤੇ ਮਿਸਾਲ ਦੇ component ਦੇਖ ਸਕਦੇ ਹੋ। ਫੇਰ quote ਲਈ phone ਕਰੋ, ਅਸੀਂ ਤੁਹਾਡੀ specific boat ਲਈ ਬਣ ਕੇ ਦੱਸਾਂਗੇ।

**Q: Ki Harris Boat Works te Punjabi vich service mildi hai? | ਕੀ Harris Boat Works ’ਤੇ ਪੰਜਾਬੀ ਵਿੱਚ service ਮਿਲਦੀ ਹੈ?**
A: ਸਾਡੇ ਕੋਲ Punjabi ਬੋਲਣ ਵਾਲਾ ਕੋਈ staff ਨਹੀਂ ਹੈ। Harris Boat Works ਦੀ team English ਵਿੱਚ ਸੇਵਾ ਦਿੰਦੀ ਹੈ। ਪਰ ਤੁਸੀਂ ਆਪਣੇ ਨਾਲ ਕੋਈ English ਜਾਣਦਾ ਸਾਥੀ ਲੈ ਆ ਸਕਦੇ ਹੋ, ਜਾਂ phone ’ਤੇ translate app ਵਰਤੋ। ਸਾਡੇ ਕੋਲ ਬਹੁਤ ਲੋਕ ਇਸ ਤਰ੍ਹਾਂ ਆਉਂਦੇ ਨੇ, ਤੇ ਕੰਮ ਆਰਾਮ ਨਾਲ ਹੋ ਜਾਂਦਾ ਹੈ। ਕੋਈ ਪਰੇਸ਼ਾਨੀ ਨਹੀਂ ਹੋਵੇਗੀ।

**Q: Nawa outboard motor khareedan layi kuch tips deyo Punjabi vich? | ਨਵਾਂ ਆਊਟਬੋਰਡ ਮੋਟਰ ਖਰੀਦਣ ਲਈ ਕੁਝ ਟਿਪਸ ਦਿਓ ਪੰਜਾਬੀ ਵਿਚ?**
A: ਜ਼ਰੂਰ। (1) ਹਮੇਸ਼ਾ installed quote ਮਨਜ਼ੂਰ ਕਰੋ, ਸਿਰਫ਼ motor ਦਾ ਮੁੱਲ ਪੁੱਛ ਕੇ ਨਾ ਰੁਕੋ। (2) Boat ਦੀ horsepower rating plate ਵੇਖ ਕੇ ਆਪਣਾ HP range ਚੁਣੋ। (3) Mercury ਦੀ 3-year warranty ਬਾਰੇ ਪੁੱਛੋ, ਅਤੇ authorized installation ਦਾ proof ਰੱਖੋ। (4) ਨਵਾਂ control box, propeller, ਅਤੇ wiring update ਕਰਨ ਲਈ ready ਰਹੋ, ਜੇ ਪੁਰਾਣੀ motor 15 ਸਾਲ ਤੋਂ ਵੱਧ ਹੈ। (5) Financing ਦੀ ਪੂਰੀ ਜਾਣਕਾਰੀ ਸਾਡੀ [English financing guide](https://www.mercuryrepower.ca/blog/mercury-outboard-financing-ontario-2026) ਵਿੱਚ ਹੈ।

**Q: Ki tuhade kolo Mercury di doosre brand naal tulna de Punjabi vich video ne? | ਕੀ ਤੁਹਾਡੇ ਕੋਲੋਂ Mercury ਦੀ ਦੂਜੇ brand ਨਾਲ ਤੁਲਨਾ ਦੇ ਪੰਜਾਬੀ ਵਿਚ ਵੀਡੀਓ ਨੇ?**
A: ਨਹੀਂ ਜੀ, ਸਾਡੇ ਕੋਲ ਕਿਸੇ brand ਦੇ comparison video ਨਹੀਂ ਨੇ। ਪਰ ਸਾਨੂੰ Mercury ਦੇ features ਬਾਰੇ ਜਾਣਨਾ ਹੈ ਤਾਂ ਸਮਝਾ ਸਕਦੇ ਹਾਂ। ਤੁਸੀਂ ਆਪਣੇ ਲਈ ਸਹੀ motor ਦਾ ਫੈਸਲਾ ਖੁਦ ਕਰ ਸਕਦੇ ਹੋ, ਸਾਡੇ quote tool ਦੇ suggest ਅਨੁਸਾਰ। Video ਵੇਖਣੀ ਹੈ ਤਾਂ YouTube ’ਤੇ general “outboard comparison” search ਕਰੋ, ਪਰ ਯਾਦ ਰੱਖੋ, ਲੋਕ ਆਪਣਾ personal opinion ਦਿੰਦੇ ਨੇ, test data ਨਹੀਂ।

**Q: Main bina dealer nu mile motor da quote labh sakda haan? | ਮੈਂ ਬਿਨਾਂ ਡੀਲਰ ਨੂੰ ਮਿਲੇ ਮੋਟਰ ਦਾ quote ਲੱਭ ਸਕਦਾ ਹਾਂ?**
A: ਜੀ ਹਾਂ, ਸਾਡੇ motor selection tool (https://www.mercuryrepower.ca/quote/motor-selection) ’ਤੇ boat details ਪਾ ਕੇ, ਤੁਹਾਨੂੰ ਕੁਝ Mercury model ਦਿਖਾਏ ਜਾਣਗੇ। ਬਾਅਦ ਵਿੱਚ ਸਾਨੂੰ call ਕਰੋ ਤਾਂ installed quote ਦੇ ਸਕਦੇ ਹਾਂ। ਇਹਦੇ ਵਿੱਚ ਕੋਈ loading ਜਾਂ pressure ਨਹੀਂ।

**Q: Main apni old motor nu trade-in de sakda haan? | ਮੈਂ ਆਪਣੀ ਪੁਰਾਣੀ ਮੋਟਰ ਨੂੰ trade-in ਦੇ ਸਕਦਾ ਹਾਂ?**
A: ਕੁਝ ਹਾਲਤਾਂ ਵਿੱਚ ਹੋ ਸਕਦਾ ਹੈ, ਪਰ ਅਸੀਂ ਹਰ ਪੁਰਾਣੀ motor ਨਹੀਂ ਲੈ ਸਕਦੇ। ਪਹਿਲਾਂ photo ਭੇਜ ਕੇ ਪੁੱਛੋ। ਦੂਜੀ ਗੱਲ: trade value installed price ਵਿੱਚ adjust ਕੀਤੀ ਜਾ ਸਕਦੀ ਹੈ, ਜੇ motor ਦੀ condition ਚੰਗੀ ਹੋਵੇ। Phone ’ਤੇ ਇਸ ਲਈ ਸਾਨੂੰ English ਵਿੱਚ ਗੱਲ ਕਰਨੀ ਹੋਵੇਗੀ, ਉੱਤੇ ਦੱਸੇ ਅਨੁਸਾਰ ਦੋਸਤ ਨਾਲ ਆਓ ਜਾਂ translation app use ਕਰੋ।

**Q: Harris Boat Works da pata ki hai? | Harris Boat Works ਦਾ ਪਤਾ ਕੀ ਹੈ?**
A: ਸਾਡਾ address 5369 Harris Boat Works Rd, Gores Landing, ON K0K 2E0 ਹੈ। Brampton, Mississauga, Scarborough, Markham ਤੋਂ ਗੱਡੀ ਰਾਹੀਂ ਤਕਰੀਬਨ 90-minute ਲੱਗਦੇ ਨੇ। ਅਸੀਂ 1 December to 1 April ਤੱਕ ਬੰਦ ਰਹਿੰਦੇ ਹਾਂ। Season ਵਿੱਚ ਸਾਨੂੰ phone (905) 342-2153 ਜਾਂ text (647) 952-2153 ਕਰੋ। Service request direct hbw.wiki/service ’ਤੇ ਜਮ੍ਹਾ ਕਰ ਸਕਦੇ ਹੋ।

## Apna quote le ke dekho | ਆਪਣਾ ਕੋਟ ਲੈ ਕੇ ਦੇਖੋ

Mercury outboard ਨਾਲ ਪੁਰਾਣੀ ਕਿਸ਼ਤੀ ਵਿੱਚ ਨਵੀਂ ਜਾਨ ਪਾਓ, ਜਾਂ ਨਵੀਂ ਕਿਸ਼ਤੀ ਦਾ dream ਪੂਰਾ ਕਰੋ, ਤੁਸੀਂ ਹੁਣ ਅਸਲ ਕੀਮਤ ਸਮਝਣ ਲਈ ready ਹੋ। ਬਿਨਾਂ ਕਿਸੇ ਝਿਜਕ ਦੇ motor ਚੋਣ ਦੀ ਸ਼ੁਰੂਆਤ ਕਰੋ:
• **Motor suggestion tool:** https://www.mercuryrepower.ca/quote/motor-selection
• **Pricing reference page:** https://www.mercuryrepower.ca/pricing-reference
• **Financing guide (English vich):** https://www.mercuryrepower.ca/blog/mercury-outboard-financing-ontario-2026
Phone ਕਰੋ (905) 342-2153, ਜੇ ਕੋਈ ਸਵਾਲ ਹੋਵੇ। ਜੇ ਤੁਸੀਂ ਆਪਣੇ phone ਰਾਹੀਂ ਇਸ guide ਨਾਲ ਜੁੜੇ ਹੋ, ਤੁਸੀਂ ਦੱਸੋ “Punjabi guide toh call kita”। ਆਪਣੀ ਕਿਸ਼ਤੀ ਦੀ ਸਹੀ Mercury ਦੀ ਯਾਤਰਾ ਅੱਜ ਸ਼ੁਰੂ ਕਰੋ।`
  }
];

export function getPunjabiArticleBySlug(slug: string): Wave1Article | undefined {
  return punjabiBlogArticles.find((a) => a.slug === slug);
}

export function getPublishedPunjabiArticles(): Wave1Article[] {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return punjabiBlogArticles.filter(article => {
    const publishDate = new Date(article.publishDate || article.datePublished);
    publishDate.setHours(0, 0, 0, 0);
    return publishDate <= today;
  });
}
