// AUTO-GENERATED by scripts/import-wave1-drafts.mjs (Wave 1 launch 2026-06-12).
// Edit drafts in /mnt/user-uploads and re-run the script rather than editing
// this file by hand. Native review status carried via the `nativeReview` field.
import type { BlogArticle } from './blogArticles';

/** Language-support FAQ answer reused wherever the "service in this language?" note appears. */
export const TL_LANGUAGE_NOTE = `Sa totoo lang, English ang ginagamit ng team namin kapag nagse-serve. Ginawa namin ang guide na ito sa Tagalog para makatulong sa komunidad, pero sa marina mismo, English ang salita. Huwag mag-alala: magdala ng kaibigan o pamilya na marunong, o gumamit ng translation app. Magiging matiyaga kami at magkakaintindihan tayo.`;

interface Wave1Article extends BlogArticle {
  /** Wave 1 native-review status. 'pending' until a native speaker signs off. */
  nativeReview?: 'pending' | 'reviewed';
  /** Original draft frontmatter internalLinks for audit. */
  internalLinks?: string[];
  /** Original draft frontmatter officialSources for audit. */
  officialSources?: string[];
}

export const tagalogBlogArticles: Wave1Article[] = [
  {
    slug: 'first-time-fishing-rice-lake-tagalog-family-guide',
    title: 'First-time fishing sa Rice Lake mula Toronto: Family Guide',
    seoTitle: 'First-time fishing sa Rice Lake mula Toronto: Family Guide',
    description: 'First-time fishing sa Rice Lake mula Toronto: fishing licence, boat rental, ano ang dadalhin, at mga family tip. Kumpletong Tagalog guide para sa pamilya.',
    image: '/lovable-uploads/hero-rice-lake-fishing-morning.png',
    author: 'Harris Boat Works',
    datePublished: '2026-06-12',
    dateModified: '2026-06-12',
    category: 'Tagalog Guide',
    readTime: '8 min basa',
    keywords: ['bangkang mura sa Ontario (cheap boat in Ontario)', 'paano bumili ng bangka sa Canada (how to buy a boat in Canada)', 'magkano ang bangka sa Toronto (how much is a boat in Toronto)', 'tips sa pagbili ng unang bangka (tips for buying first boat)', 'fishing license Ontario paano kumuha (fishing license Ontario how to get)', 'saan mangisda malapit sa Toronto (where to fish near Toronto)', 'Ontario fishing rules Tagalog (Ontario fishing rules Tagalog)', 'panahon ng pangingisda sa Ontario (fishing season in Ontario)', 'magkano fishing license sa Ontario (how much fishing license in Ontario)', 'pangingisda sa Rice Lake Ontario (fishing at Rice Lake Ontario)'],
    faqs: [
      { question: 'Paano kumuha ng fishing license sa Ontario?', answer: 'Pumunta sa ServiceOntario o mag-online sa official website. Kailangan ng Outdoors Card (plastic card o paper temporary) at pagkatapos ay piliin ang conservation o sport fishing licence na babagay sa pamilya ninyo. Ang buong process ay nasa [page ng Ontario fishing licence](https://www.ontario.ca/page/fishing-licence-ontario-and-canadian-residents).' },
      { question: 'Magkano ang fishing license sa Ontario?', answer: 'Ang istruktura ng bayad ay: hiwalay ang bayad para sa Outdoors Card, at hiwalay ang bayad para sa fishing licence (conservation licence ay mas mura, sport licence mas mahal). Ang updated at eksaktong dollar amounts ay palaging nasa opisyal na website, kaya imbes na magbigay kami ng number na baka luma na, please check ang [Outdoors Card at licence summary](https://www.ontario.ca/page/get-outdoors-card-and-licence-summary) at ang [fishing licence page](https://www.ontario.ca/page/fishing-licence-ontario-and-canadian-residents).' },
      { question: 'Saan pwedeng mangisda malapit sa Toronto?', answer: 'Ang Rice Lake sa Gores Landing ay isa sa pinaka-accessible, mga 90 minutos lang mula sa Mississauga, Scarborough, Brampton, o Markham. Hindi tulad ng malalim na Lake Ontario, mababaw at beginner-friendly ito, kaya safe para sa pamilya.' },
      { question: 'Ano ang mga fishing rules sa Ontario para sa Rice Lake?', answer: 'Ang Rice Lake ay bahagi ng FMZ 17. Ang bawat uri ng isda ay may sariling season, daily catch limit, at size restrictions. Halimbawa, magkaiba ang rules para sa panfish (crappie, bluegill) at sa walleye. Dahil taun-taon itong pwedeng magbago, kailangang i-check ninyo ang opisyal na [Ontario Fishing Regulations Summary](https://www.ontario.ca/document/ontario-fishing-regulations-summary) bago kayo mangisda. Iyan ang laging tama.' },
      { question: 'Kailangan ko ba ng sariling bangka para mangisda sa Rice Lake?', answer: 'Hindi. May rental fleet ang Harris Boat Works na puwedeng gamitin kahit walang PCOC. Bibigyan namin kayo ng safety checklist at orientation, at may lifejackets para sa lahat, pati kids. Pumunta lang sa aming [rentals page](https://harrisboatworks.ca/rentals).' },
      { question: 'Paano kung hindi ako marunong mag-drive ng bangka?', answer: 'Okay lang. Kasama sa rental ang basic orientation, kontrol sa throttle, steering, at safety. Ang mga bangka namin ay simple at stable, perpekto para sa first-timer. Tuturuan namin kayo hanggang maging komportable.' },
      { question: 'Bangkang mura sa Ontario o tips sa pagbili ng unang bangka?', answer: 'Para sa maraming pamilya, ang pag-rent muna ang pinakamadaling paraan para subukan kung bagay sa inyo ang frequent boating. Kung desidido na kayong bumili, ang Harris Boat Works ay Mercury dealer mula pa 1965 at nag-aalok ng mga bagong bangka. Ang Mercury motors ay may 3-year base warranty. Para sa pagpili ng tamang bangka, bisitahin kami o tawagan kami. Ang detalye tungkol sa financing ay nasa aming English guide: https://www.mercuryrepower.ca/blog/mercury-outboard-financing-ontario-2026' },
      { question: 'Pwede ba akong makakuha ng serbisyo sa Tagalog sa Harris Boat Works?', answer: 'Sa totoo lang, English ang ginagamit ng team namin kapag nagse-serve. Ginawa namin ang guide na ito sa Tagalog para makatulong sa komunidad, pero sa marina mismo, English ang salita. Huwag mag-alala: magdala ng kaibigan o pamilya na marunong, o gumamit ng translation app. Magiging matiyaga kami at magkakaintindihan tayo.' }
    ],
    nativeReview: 'pending',
    internalLinks: ['https://harrisboatworks.ca/rentals'],
    officialSources: ['https://www.ontario.ca/page/fishing-licence-ontario-and-canadian-residents', 'https://www.ontario.ca/page/get-outdoors-card-and-licence-summary', 'https://www.ontario.ca/page/learn-fish', 'https://www.ontario.ca/document/ontario-fishing-regulations-summary'],
    content: `Rice Lake ang pinakamagandang unang subok na pangingisda para sa pamilyang Pilipino sa Toronto. Mga 90 minuto ang biyahe mula Brampton, Mississauga, Scarborough, o Markham, at dito sa Harris Boat Works, gagawin naming simple at masaya ang inyong araw kahit baguhan kayo, may rental boat na, lifejacket para sa kids, at fishing license guidance.

## Bakit Rice Lake?

Ang Rice Lake ay mababaw, kalmado, at kilala bilang beginner-friendly na lawa para sa mga bata, perpekto para sa unang family fishing trip. Sa halip na malalim at nakakatakot na lawa, ito ay warm, protected, at hindi mo kailangan ng malaking bangka. Matatagpuan ito sa Gores Landing, na nasa FMZ 17 (Fisheries Management Zone 17), at kilala sa panfish tulad ng bluegill at crappie, pati na rin sa walleye, pero walang pwedeng mangako kung gaano karami ang mahuhuli ninyo. Ang importante, masaya ang experience at maraming matututunan ang pamilya.

## Ang biyahe mula Toronto, Mississauga, o Scarborough

Halos 90 minuto lang ang biyahe. Mula sa Brampton, Mississauga, Scarborough, o Markham, pare-pareho ang tagal, gamitin ang GPS papunta sa aming address sa Gores Landing. Ang marina namin ay nasa 5369 Harris Boat Works Rd, Gores Landing, ON K0K 2E0. May parking, at sasalubungin kayo ng team namin pagdating ninyo.

## Ano ang kailangan ninyong dalhin

* **Fishing licence** para sa bawat magulang o adult na mangingisda (karaniwang hindi kailangan ng licence ang mga batang Ontario resident na wala pang 18, pero kailangang sundin ang rules at limits; i-check ang official page: https://www.ontario.ca/page/fishing-licence-ontario-and-canadian-residents). Hindi kailangan ng lisensya kung sasali kayo sa libreng Learn to Fish program (more on that below).
* **Sun protection**, sumbrero, sunscreen, at polarized sunglasses para hindi masilaw at makita ang isda.
* **Snacks at tubig**, walang mahuhuling isda sa gutom na tiyan. Magbaon ng paboritong merienda ng pamilya.
* **Camera o phone**, para sa mga hindi makakalimutang kuha ng unang huli ng anak ninyo.
* **Warm layer**, kahit summer, ang umaga sa lawa ay maaaring presko.

### Fishing licence para sa Ontario

Para makapangisda ang sinumang residente ng Ontario na 18 anyos pataas, kailangan ng dalawang bagay:

1. **Outdoors Card**, ito ang plastic card na nagpapatunay na rehistrado ka sa provincial system. Kailangan ito bago ka makabili ng fishing licence tag.
2. **Fishing licence**, may dalawang uri: **Conservation licence** (mas mababang daily catch limits, mas mura) at **Sport licence** (mas maraming puwedeng ihuli). Para sa pamilyang first-timer, madalas ang conservation licence ang praktikal, sapat na iyon para maranasan ang saya ng pangingisda nang hindi kumplikado.

Ang eksaktong bayarin (Outdoors Card plus licence, conservation o sport) ay nakalista sa opisyal na website ng Ontario. Pakitingnan ang kasalukuyang fees dito: [Ontario fishing licence for residents](https://www.ontario.ca/page/fishing-licence-ontario-and-canadian-residents) at [Outdoors Card at licence summary](https://www.ontario.ca/page/get-outdoors-card-and-licence-summary). Tandaan: hindi ito legal advice, ang opisyal na pahina ang laging masusunod, dahil pwedeng magbago ang mga patakaran.

**Libreng opsyon: Learn to Fish program.** Ang Ontario ay may [Learn to Fish](https://www.ontario.ca/page/learn-fish) program na nagtuturo ng basics, madalas libreng gamit at walang lisensyang kailangan habang nasa session ka. Mainam ito para sa pamilyang gustong subukan muna bago bumili ng lisensya. Check ninyo ang schedule ng mga klase malapit sa inyo.

**Mahalaga:** Ang Rice Lake ay nasa FMZ 17. Ang bawat species ng isda ay may sariling season, daily limit, at size rules. Dahil nagbabago ang mga ito, huwag umasa sa mga lumang impormasyon. Basahin ang [Ontario Fishing Regulations Summary](https://www.ontario.ca/document/ontario-fishing-regulations-summary) bago kayo pumunta para malaman ang kasalukuyang patakaran sa panfish, walleye, at iba pa.

## Pangingisda kasama ang pamilya: walang experience? Okay lang!

Hindi ninyo kailangan ng sariling bangka o kahit ng PCOC (Pleasure Craft Operator Card) para makapangisda sa Rice Lake. Sa Harris Boat Works, nagre-rent kami ng 9 na bangka na kumpleto sa safety gear at maaaring gamitin nang walang boat licence, ang kailangan lang ay pakinggan ang aming rental safety checklist at orientation bago kayo lumarga. Ibibigay namin ang lifejackets para sa lahat, kasama ang tamang sukat para sa mga bata. Walang experience sa pagmamando? Tuturuan namin kayo ng basic controls. Mas makakampante kayo.

Puwede ninyong i-book ang rental boat sa aming [rentals page](https://harrisboatworks.ca/rentals). Tandaan: sarado ang marina mula December 1 hanggang April 1, kaya planuhin ang trip sa pagitan ng tagsibol at taglagas.

## Ano ang aasahan sa isang araw ng pangingisda sa Rice Lake

Isipin ninyo: umaga ng Sabado, umalis ng bahay bandang 7:00, dating sa marina bago mag-9:00. Pagdating ninyo, ise-set up namin ang bangka, brief orientation, at tuturo ang mga promising spots. Sa unang dalawang oras, maaaring makahuli ang mga bata ng bluegill o crappie, pero tulad ng lahat ng pangingisda, walang garantiya. Puwede rin kayong mag-target ng walleye kung handa kayong maghintay at subukan ang mas malalim na bahagi, pero walang garantiya; minsan mahirap silang hulihin. Ang totoo, may mga araw na mabagal ang bite, pero ang bonding ng pamilya sa bangka, tawanan, meryenda, pagtuturo sa isa’t isa, ang tunay na panalo. Pagkatapos ng ilang oras, babalik kayo, magpapahinga sa tabing-lawa, at magkukuwentuhan tungkol sa mga “dapat sana” na isda.

Ang mahalaga: huwag mag-expect ng bucketful ng walleye. Ang Rice Lake ay tungkol sa accessible, beginner-friendly fishing na puno ng panfish, perfect para sa kids at mga bagong mamimingwit.

## Isang tapat na mensahe mula sa aming team

Ginawa namin ang guide na ito sa Tagalog dahil gusto talaga naming tulungan ang mga kababayan nating Pilipino, pati na ang kanilang pamilya at mga kaibigan, na ma-enjoy ang Rice Lake. Ilang marinas ang sumusubok na abutin ang komunidad sa ganitong paraan, at mahalaga sa amin na maramdaman ninyong welcome kayo. Pero sa totoo lang, ang aming team ay nagse-serve in English, ito ang working language namin. Huwag po kayong mag-alala: magdala ng kaibigan o kapamilya na marunong mag-English, o gumamit ng translation app sa phone ninyo. Magiging matiyaga kami, ipapaliwanag ang lahat nang dahan-dahan, at magkakaintindihan tayo. Ang goal namin ay maging komportable kayo at makauwing may ngiti.

## FAQ (Mga Madalas Itanong)

**Paano kumuha ng fishing license sa Ontario?**
Pumunta sa ServiceOntario o mag-online sa official website. Kailangan ng Outdoors Card (plastic card o paper temporary) at pagkatapos ay piliin ang conservation o sport fishing licence na babagay sa pamilya ninyo. Ang buong process ay nasa [page ng Ontario fishing licence](https://www.ontario.ca/page/fishing-licence-ontario-and-canadian-residents).

**Magkano ang fishing license sa Ontario?**
Ang istruktura ng bayad ay: hiwalay ang bayad para sa Outdoors Card, at hiwalay ang bayad para sa fishing licence (conservation licence ay mas mura, sport licence mas mahal). Ang updated at eksaktong dollar amounts ay palaging nasa opisyal na website, kaya imbes na magbigay kami ng number na baka luma na, please check ang [Outdoors Card at licence summary](https://www.ontario.ca/page/get-outdoors-card-and-licence-summary) at ang [fishing licence page](https://www.ontario.ca/page/fishing-licence-ontario-and-canadian-residents).

**Saan pwedeng mangisda malapit sa Toronto?**
Ang Rice Lake sa Gores Landing ay isa sa pinaka-accessible, mga 90 minutos lang mula sa Mississauga, Scarborough, Brampton, o Markham. Hindi tulad ng malalim na Lake Ontario, mababaw at beginner-friendly ito, kaya safe para sa pamilya.

**Ano ang mga fishing rules sa Ontario para sa Rice Lake?**
Ang Rice Lake ay bahagi ng FMZ 17. Ang bawat uri ng isda ay may sariling season, daily catch limit, at size restrictions. Halimbawa, magkaiba ang rules para sa panfish (crappie, bluegill) at sa walleye. Dahil taun-taon itong pwedeng magbago, kailangang i-check ninyo ang opisyal na [Ontario Fishing Regulations Summary](https://www.ontario.ca/document/ontario-fishing-regulations-summary) bago kayo mangisda. Iyan ang laging tama.

**Kailangan ko ba ng sariling bangka para mangisda sa Rice Lake?**
Hindi. May rental fleet ang Harris Boat Works na puwedeng gamitin kahit walang PCOC. Bibigyan namin kayo ng safety checklist at orientation, at may lifejackets para sa lahat, pati kids. Pumunta lang sa aming [rentals page](https://harrisboatworks.ca/rentals).

**Paano kung hindi ako marunong mag-drive ng bangka?**
Okay lang. Kasama sa rental ang basic orientation, kontrol sa throttle, steering, at safety. Ang mga bangka namin ay simple at stable, perpekto para sa first-timer. Tuturuan namin kayo hanggang maging komportable.

**Bangkang mura sa Ontario o tips sa pagbili ng unang bangka?**
Para sa maraming pamilya, ang pag-rent muna ang pinakamadaling paraan para subukan kung bagay sa inyo ang frequent boating. Kung desidido na kayong bumili, ang Harris Boat Works ay Mercury dealer mula pa 1965 at nag-aalok ng mga bagong bangka. Ang Mercury motors ay may 3-year base warranty. Para sa pagpili ng tamang bangka, bisitahin kami o tawagan kami. Ang detalye tungkol sa financing ay nasa aming English guide: https://www.mercuryrepower.ca/blog/mercury-outboard-financing-ontario-2026

**Pwede ba akong makakuha ng serbisyo sa Tagalog sa Harris Boat Works?**
Sa totoo lang, English ang ginagamit ng team namin kapag nagse-serve. Ginawa namin ang guide na ito sa Tagalog para makatulong sa komunidad, pero sa marina mismo, English ang salita. Huwag mag-alala: magdala ng kaibigan o pamilya na marunong, o gumamit ng translation app. Magiging matiyaga kami at magkakaintindihan tayo.

## Tara na sa Rice Lake!

Ang unang family fishing trip ay mas madali kaysa sa iniisip ninyo. Bisitahin ang aming [rentals page](https://harrisboatworks.ca/rentals) para simulan ang plano, o tawagan kami. Bukas ang Harris Boat Works mula tagsibol hanggang taglagas, at sarado tuwing December 1 hanggang April 1.

**Makipag-ugnayan sa amin**  
Telepono: (905) 342-2153  
Text: (647) 952-2153  
Service requests: [hbw.wiki/service](https://hbw.wiki/service)  
Address: 5369 Harris Boat Works Rd, Gores Landing, ON K0K 2E0

Hatid namin ang karanasan sa lawa na maaalala ng inyong pamilya, tunay, simple, at walang kaba.`
  },
  {
    slug: 'ontario-boat-rental-rules-tagalog-pcoc',
    title: 'Boat rental rules sa Ontario: PCOC, checklist, lifejackets (Tagalog Guide)',
    seoTitle: 'Boat rental rules sa Ontario: PCOC, checklist, lifejackets (Tagalog Guide)',
    description: 'Kailangan ba ng PCOC para mag-rent ng boat sa Ontario? Rental rules, lifejacket requirements, at checklist bago bumangka. Tagalog guide para sa pamilya mo.',
    image: '/lovable-uploads/hero-first-time-boat-rental.webp',
    author: 'Harris Boat Works',
    datePublished: '2026-06-12',
    dateModified: '2026-08-01',
    category: 'Tagalog Guide',
    readTime: '8 min basa',
    keywords: ['paano kumuha ng boat license sa Ontario (how to get a boat license in Ontario)', 'kailangan ba ng boat license sa Ontario (is a boat license required in Ontario)', 'boat operator card Ontario paano (boat operator card Ontario how)', 'online boat license Ontario Tagalog (online boat license Ontario Tagalog)', 'PCOC exam Tagalog (PCOC exam Tagalog)'],
    faqs: [
      { question: 'Kailangan ba ng boat license sa Ontario para magmaneho ng bangka?', answer: 'Kung may sarili kang bangka na may motor, oo, kailangan ng Pleasure Craft Operator Card (PCOC). Pero kung magre-rent ka, hindi ito kailangan, ang rental boat safety checklist ang papalit, tulad ng ginagawa namin sa HBW.' },
      { question: 'Paano kumuha ng boat license (PCOC) sa Ontario?', answer: 'Mag-enroll sa isang accredited online course, mag-aral ng safety materials, at sagutan ang multiple-choice exam. Kapag nakapasa, bibigyan ka ng PCOC na valid habang buhay. Tingnan ang listahan ng providers dito: [https://tc.canada.ca/en/marine-transportation/buying-boat/find-education-resources-recreational-boaters](https://tc.canada.ca/en/marine-transportation/buying-boat/find-education-resources-recreational-boaters). Walang official na Tagalog version ang exam; nasa English o French lang ito.' },
      { question: 'May serbisyo ba kayo sa Tagalog sa Harris Boat Works?', answer: 'Sa totoo lang, ang team namin ay nagseserbisyo sa Ingles. Pero huwag mag-alala, magsama ng kaibigan o kapamilya na marunong mag-English, o magdala ng translation app. Magtutulungan tayo. (Basahin ang buong pahayag sa itaas.)' },
      { question: 'Mayroon bang PCOC exam na Tagalog?', answer: 'Wala pong opisyal na PCOC exam na Tagalog. Lahat ng accredited exams ay nasa English o French. May ilang community-made translation guides na makikita online, pero hindi ito official. Ang pinakamainam na gawin ay mag-aral gamit ang English study guide, at kung nahihirapan, magpatulong sa marunong mag-English. Kayang-kaya ito kapag pamilyar ka sa basic boat terms.' },
      { question: 'Ano ang mangyayari kapag nahuli akong may bukas na alak sa bangka?', answer: 'Malaking problema ito. Ang open alcohol sa recreational boat ay ilegal, at ang pagmamaneho habang nakainom ay criminal offense, pwedeng maaresto, mawalan ng lisensya, matiketan ng malaking multa, at ma-impound ang bangka. Huwag nang subukan. Gawin ang inuman sa pampang pagkatapos ng biyahe.' },
      { question: 'Kailangan bang mag-lifejacket ang bata kahit marunong siyang lumangoy?', answer: 'Oo. Walang exception. Lahat ng bata ay dapat suot ang lifejacket na tamang sukat (may crotch strap para sa maliliit) habang umaandar ang bangka. Hindi sapat na marunong lumangoy, sa emergency, ang lifejacket ang sasagip ng buhay.' },
      { question: 'Pwede bang mag-rent ng bangka kahit wala akong experience?', answer: 'Siyempre. Ito mismo ang dahilan kung bakit may rental boat safety checklist. Gagabayan ka namin mula pagdating hanggang sa maging komportable ka. Pakiusap lang, maging tapat sa amin tungkol sa experience level mo para mas maayos ang briefing.' },
      { question: 'Gaano katagal ang biyahe mula Toronto papuntang Harris Boat Works?', answer: 'Mga 90 minuto mula sa Brampton, Mississauga, Scarborough, o Markham. Malapit lang ito para sa isang araw ng pamilya, umaga kang aalis, buong araw sa lawa, at hapon ang uwi.' }
    ],
    nativeReview: 'pending',
    internalLinks: ['https://harrisboatworks.ca/rentals'],
    officialSources: ['https://tc.canada.ca/en/marine-transportation/preparing-operate-your-vessel/pleasure-craft-operator-card-pcoc', 'https://tc.canada.ca/en/marine-transportation/buying-boat/find-education-resources-recreational-boaters'],
    content: `Hindi kailangan ng PCOC para mag-rent ng boat sa Ontario, basta kukumpletuhin mo ang rental boat safety checklist kasama ang rental company. Mula sa pamilya ng Harris Boat Works sa Gores Landing, gusto ka naming tulungan, lalo na ang mga kababayan nating Filipino sa Toronto, Mississauga, at buong GTA, na ma-enjoy ang Rice Lake nang walang kaba. Malapit lang kami: mga 90 minutong drive mula sa Brampton, Mississauga, Scarborough, o Markham. Kahit never ka pa sumakay ng bangka sa Canada, dito ka safe na magsisimula. Ito ang dapat mong malaman tungkol sa boat rental rules, lifejackets, at kung paano gumagana ang sistema dito.

## Hindi mo kailangan ng PCOC para mag-rent ng bangka

Diretso ang sagot: **hindi** kailangan ng Pleasure Craft Operator Card (PCOC), o boat license na karaniwang tawag, kapag nagre-rent ka ng bangka sa Ontario. Ang kailangan mo lang ay dumaan sa isang simpleng *rental boat safety checklist* kasama ang rental operator. Ibig sabihin, kahit unang beses mo, pwedeng pwede kang mag-boat. Walang exam, walang lisensya, basta handa kang makinig at sundin ang safety rules para sa pamilya mo.

## Ang rental boat safety checklist: Ano ito at paano gamitin

Ang checklist ay gawa ng Transport Canada para siguradong alam mo ang basics bago ka umalis. Sa Harris Boat Works, kapag dumating ka, sasamahan ka ng team namin at ipapaliwanag ang bawat punto sa checklist. Hindi ito pormal na oral exam, kundi isang maikling briefing na ginagawa naming kalmado at malinaw.

Karaniwang kasama sa checklist:

- Saan nakatago ang lifejackets at tamang paraan ng pagsuot nito
- Lokasyon ng fire extinguisher, flashlight, at ibang safety equipment
- Paano paandarin ang bangka: throttle, steering, at emergency shut-off
- Mga local rule sa Rice Lake: speed limits, no-wake zones, at navigation markers
- Ano ang gagawin kapag masama ang panahon
- Panganib sa mababaw na lugar at submerged na bato

Pagkatapos ng briefing, pipirmahan mo na naiintindihan mo lahat. Simple lang, pero huwag mong balewalain, para ito sa kapakanan ng lahat ng sakay.

## Lifejacket rules: Seryoso, walang lusot

Sa Ontario, ang lifejacket o personal flotation device (PFD) ay hindi optional. Bawat tao na nasa bangka, bata man o matanda, ay dapat may sariling lifejacket na tamang-tama ang sukat. Dito sa amin, may mga lifejackets kami para sa iba't ibang sukat, kasama ang pambata, at tinitiyak naming malinis at nasa ayos ang mga ito.

Para sa bata: kailangan naka-lifejacket na may crotch strap (yung pumapagitna sa legs) at akma sa timbang ng bata. I-che-check ng staff namin ang fit bago umalis. Ayon sa batas, kailangang may tamang-sukat na lifejacket o PFD para sa bawat tao sa bangka. Mariin naming inirerekomenda na **suot ito palagi** habang umaandar ang bangka, lalo na ng mga bata. Simple lang ang rason: sa emergency, hindi na magkakaroon ng oras para maghanap at magsuot ng lifejacket.

## Alcohol sa bangka: Seryosong babala

Please, pakinggan ito nang buong atensyon. Ang alcohol sa bangka ay tinatrato ng batas na kapareho ng pag-inom habang nagmamaneho ng kotse. Bawal ang open liquor sa loob ng recreational boat, maliban lang kung ang bangka ay may permanenteng kusina, CR, at higaan (malalaking yate lang ito, hindi ang nire-rent na maliliit na fishing boat). Ang pagmamaneho ng bangka habang lasing ay isang criminal offense: pwedeng magresulta sa pagkakaaresto, suspensyon ng driver's license mo, malaking multa, at impound ng bangka.

Mas mabuti na ang inuman gawin sa pampang, pagkatapos ng boating trip, hindi habang nasa tubig. Iniisip namin ang pamilya mo, ang passengers mo, at ang ibang tao sa lawa. Seryosohin ito.

## Ano ang responsibilidad mo bilang renter

Kapag nirentahan mo ang bangka, ikaw ang may pananagutan sa pagbabalik nito sa oras at nasa kondisyong katulad noong kinuha mo. Ibig sabihin:

- I-report agad ang anumang sira o problema, kahit maliit
- Mag-ingat sa propeller at sa ilalim ng bangka, huwag lumapit sa mababaw na lugar o bato na nakatago sa ilalim ng tubig (ituturo namin sa briefing kung aling areas ang iiwasan)
- Sundin ang lahat ng patakaran na ipinaliwanag sa safety briefing
- Kung may damage dahil sa iyong kapabayaan, pwede kang singilin; kaya umiwas sa mga sitwasyong peligroso

Tutulungan ka namin bago ka pumalaot, magtatanong kami, magpapaliwanag, at sisiguruhing confident kang magmaneho. Pero ang bottom line, ikaw ang driver, kaya maging responsable.

## Ang HBW rental fleet

Mayroon kaming rental fleet na may mga pontoon at fishing boat. Sakto ito para sa pamilya: pwedeng mag-fishing, mag-cruise at magpicture-picture, o mag-relax lang sa tahimik na bahagi ng Rice Lake. Tingnan ang kasalukuyang fleet at availability sa harrisboatworks.ca/rentals. Ethanol-free ang gasolina namin on site.

Hindi kami maglalagay ng presyo dito, ang lahat ng detalye tungkol sa rates at availability ay nandito sa aming rentals page: [https://harrisboatworks.ca/rentals](https://harrisboatworks.ca/rentals). Tumingin doon para makapag-plano ng trip ngayong season.

## Paano kumuha ng boat license (PCOC) kung gusto mo ng sariling bangka

Gets namin, maraming nagtatanong tungkol sa boat license, kahit hindi kailangan sa rental, posibleng balang araw gusto mo nang bumili ng sariling bangka o mag-rent sa ibang lugar na walang safety checklist. Sa ganong pagkakataon, kailangan mo ng Pleasure Craft Operator Card (PCOC).

Ang PCOC ay kinukuha sa pamamagitan ng pagpasa sa isang accredited online exam. Walang praktikal na driving test; puro multiple-choice questions lang tungkol sa boating safety, navigation rules, emergency procedures, at kung paano magbasa ng mga lawa at ilog. Bago mag-exam, mag-aral ka gamit ang study guide mula sa provider. Listahan ng mga accredited provider ay narito: [https://tc.canada.ca/en/marine-transportation/buying-boat/find-education-resources-recreational-boaters](https://tc.canada.ca/en/marine-transportation/buying-boat/find-education-resources-recreational-boaters). May bayad ang exam, pero ang card na makukuha mo ay panghabambuhay na, hindi na kailangan i-renew.

Mahalagang paalala: ito ay pangkalahatang impormasyon lamang, hindi ito legal advice. Maaaring magbago ang rules. Palaging panalo ang opisyal na website: [https://tc.canada.ca/en/marine-transportation/preparing-operate-your-vessel/pleasure-craft-operator-card-pcoc](https://tc.canada.ca/en/marine-transportation/preparing-operate-your-vessel/pleasure-craft-operator-card-pcoc).

## Ang aming tapat na pahayag

Ginawa namin ang gabay na ito sa Tagalog dahil gusto naming makatulong sa ating Filipino boaters, kayo at ang inyong pamilya at kaibigan, na ma-enjoy ang Rice Lake. Kokonti lang ang gumagawa ng ganito para sa komunidad, kaya ito ang ambag namin.

Pero maging tapat tayo: ang aming team ay nagseserbisyo sa Ingles. Huwag mag-alala. Magsama ng kaibigan o kapamilya na marunong mag-English, o gumamit ng translation app sa telepono. Matiyaga kami, at magtutulungan tayo para magawa ito nang maayos. Ang mahalaga, maramdaman mong welcome ka rito.

## FAQ: Mga Karaniwang Tanong

**Kailangan ba ng boat license sa Ontario para magmaneho ng bangka?**  
Kung may sarili kang bangka na may motor, oo, kailangan ng Pleasure Craft Operator Card (PCOC). Pero kung magre-rent ka, hindi ito kailangan, ang rental boat safety checklist ang papalit, tulad ng ginagawa namin sa HBW.

**Paano kumuha ng boat license (PCOC) sa Ontario?**  
Mag-enroll sa isang accredited online course, mag-aral ng safety materials, at sagutan ang multiple-choice exam. Kapag nakapasa, bibigyan ka ng PCOC na valid habang buhay. Tingnan ang listahan ng providers dito: [https://tc.canada.ca/en/marine-transportation/buying-boat/find-education-resources-recreational-boaters](https://tc.canada.ca/en/marine-transportation/buying-boat/find-education-resources-recreational-boaters). Walang official na Tagalog version ang exam; nasa English o French lang ito.

**May serbisyo ba kayo sa Tagalog sa Harris Boat Works?**  
Sa totoo lang, ang team namin ay nagseserbisyo sa Ingles. Pero huwag mag-alala, magsama ng kaibigan o kapamilya na marunong mag-English, o magdala ng translation app. Magtutulungan tayo. (Basahin ang buong pahayag sa itaas.)

**Mayroon bang PCOC exam na Tagalog?**  
Wala pong opisyal na PCOC exam na Tagalog. Lahat ng accredited exams ay nasa English o French. May ilang community-made translation guides na makikita online, pero hindi ito official. Ang pinakamainam na gawin ay mag-aral gamit ang English study guide, at kung nahihirapan, magpatulong sa marunong mag-English. Kayang-kaya ito kapag pamilyar ka sa basic boat terms.

**Ano ang mangyayari kapag nahuli akong may bukas na alak sa bangka?**  
Malaking problema ito. Ang open alcohol sa recreational boat ay ilegal, at ang pagmamaneho habang nakainom ay criminal offense, pwedeng maaresto, mawalan ng lisensya, matiketan ng malaking multa, at ma-impound ang bangka. Huwag nang subukan. Gawin ang inuman sa pampang pagkatapos ng biyahe.

**Kailangan bang mag-lifejacket ang bata kahit marunong siyang lumangoy?**  
Oo. Walang exception. Lahat ng bata ay dapat suot ang lifejacket na tamang sukat (may crotch strap para sa maliliit) habang umaandar ang bangka. Hindi sapat na marunong lumangoy, sa emergency, ang lifejacket ang sasagip ng buhay.

**Pwede bang mag-rent ng bangka kahit wala akong experience?**  
Siyempre. Ito mismo ang dahilan kung bakit may rental boat safety checklist. Gagabayan ka namin mula pagdating hanggang sa maging komportable ka. Pakiusap lang, maging tapat sa amin tungkol sa experience level mo para mas maayos ang briefing.

**Gaano katagal ang biyahe mula Toronto papuntang Harris Boat Works?**  
Mga 90 minuto mula sa Brampton, Mississauga, Scarborough, o Markham. Malapit lang ito para sa isang araw ng pamilya, umaga kang aalis, buong araw sa lawa, at hapon ang uwi.

## Handa nang mag-boat?

Tingnan ang aming rental fleet at magpareserba dito: [https://harrisboatworks.ca/rentals](https://harrisboatworks.ca/rentals)

Para sa ibang tanong, tawagan o i-text kami:  
📞 (905) 342-2153  
📱 Text: (647) 952-2153  
Para sa service requests: [hbw.wiki/service](https://hbw.wiki/service)

Matatagpuan kami sa: 5369 Harris Boat Works Rd, Gores Landing, ON K0K 2E0. Tandaan lang, sarado ang marina mula December 1 hanggang April 1. Inaasahan ka namin, magkita tayo sa Rice Lake!`
  },
  {
    slug: 'outboard-service-winterization-tagalog',
    title: 'Outboard motor service at winterization sa Ontario (Tagalog Guide)',
    seoTitle: 'Outboard motor service at winterization sa Ontario (Tagalog Guide)',
    description: 'Outboard motor service at winterization sa Ontario: kailan, bakit, at saan magpapa-service ng Mercury motor mo. Tagalog guide mula sa Rice Lake na marina.',
    image: '/lovable-uploads/diy-mercury-winterization-hero.jpg',
    author: 'Harris Boat Works',
    datePublished: '2026-06-12',
    dateModified: '2026-08-01',
    category: 'Tagalog Guide',
    readTime: '8 min basa',
    keywords: ['mekaniko ng bangka sa Toronto (boat mechanic in Toronto)', 'pagawaan ng motor ng bangka malapit sa Mississauga (boat motor repair shop near Mississauga)', 'marine mechanic Pilipino Toronto (Filipino marine mechanic Toronto)', 'paano i-winterize ang bangka (how to winterize a boat)', 'paghahanda ng bangka sa taglamig (preparing boat for winter)', 'winter storage ng bangka Ontario (winter storage of boat Ontario)', 'winterization service bangka Toronto (winterization service boat Toronto)', 'paano ayusin ang Mercury outboard (how to fix Mercury outboard)'],
    faqs: [
      { question: 'Saan makakahanap ng mekaniko ng bangka sa Toronto?', answer: 'Ang HBW ay nasa Gores Landing, malapit sa Rice Lake, mga 90 minutong biyahe mula Brampton, Mississauga, Scarborough, at Markham. Walang malapit na shop sa loob ng Toronto na mare-rekomenda namin, pero maraming may-ari ng Mercury ang pumipiling mag-drive papunta sa amin dahil sa aming kadalubhasaan. Kung gusto mong makasigurado sa certified service, puntahan kami.' },
      { question: 'May marine mechanic ba na Pilipino sa Toronto?', answer: 'Wala pong Pilipinong mechanic sa HBW. Ang lahat ng aming technician ay bihasa sa Mercury pero ang lengguwahe ng shop ay English. Ang serbisyo namin ay sa English, kaya magdala ng kasamang marunong mag-English o gumamit ng translation app; matiyaga naming aasikasuhin ang kailangan mo.' },
      { question: 'Paano i-winterize ang bangka?', answer: 'Ang professional winterization ay binubuo ng pag-drain ng tubig, pag-fog sa cylinders, paglalagay ng fuel stabilizer, pagpalit ng gear oil, at marami pang hakbang para protektahan ang makina sa lamig. Puwede mong gawin ito nang sarili kung may experience ka, pero kung bago ka pa lang, mas safe na ipagawa sa certified shop tulad ng HBW. Tingnan ang aming winterization service para sa detalyadong breakdown.' },
      { question: 'Saan ang winter storage ng bangka sa Ontario?', answer: 'Nag-aalok ang HBW ng winter storage sa aming marina sa Gores Landing, at puwedeng isabay ito sa winterization ng motor. Napupuno ang storage tuwing fall, kaya mag-book nang maaga bago ang December 1. Magtanong sa https://hbw.wiki/service.' },
      { question: 'Paano ayusin ang Mercury outboard?', answer: 'Kung Mercury o Mercruiser ang motor mo, dalhin mo sa amin. Umpisahan namin ito ng computer diagnostic kung applicable, visual inspection, at pag-check ng fuel, spark, at compression. Certified technicians ang gagawa, at purong Mercury parts lang ang gagamitin. Kung may warranty ka, protektado ito kapag sa amin ka nagpagawa.' },
      { question: 'Saan ang pagawaan ng motor ng bangka malapit sa Mississauga?', answer: 'Walang partikular na shop sa Mississauga na mare-rekomenda namin. Ang HBW ay mula sa Gores Landing, mga 90 minuto ang biyahe, pero marami kaming customer na galing Mississauga dahil sa kumpiyansa nila sa aming Mercury expertise. Kung handa kang mag-drive, welcome ka rito.' },
      { question: 'Puwede ba akong makakuha ng serbisyo sa Tagalog sa HBW?', answer: 'Hindi po. Ang aming team ay nagsisilbi sa English lamang. Pero huwag mahiya: magsama ng kaibigan o pamilya na marunong mag-Ingles, o gumamit ng translation app. Magiging matiyaga kami sa pagpapaliwanag hanggang maintindihan mo nang lubos.' }
    ],
    nativeReview: 'pending',
    internalLinks: ['https://hbw.wiki/service'],
    officialSources: [],
    content: `Alam namin: nakakapanibago magmay-ari ng bangka dito sa Canada. ‘Yung mga tanong tungkol sa makina, sa pag-iingat tuwing taglamig, at kung sino ang mapagkakatiwalaang mag-ayos, normal lang ‘yan lalo na kung bagong salta sa boating scene. Kami sa Harris Boat Works (HBW), pamilya ang nagpapatakbo ng marina sa Rice Lake mula pa noong 1947, at Mercury dealer na kami simula 1965. Kaya sa gabay na ito, ipapaliwanag namin sa paraang parang kaibigan lang ang kailangan mong malaman tungkol sa serbisyo ng outboard motor, winterization, at kung paano panatilihing malusog ang makina mo sa klima ng Ontario.

## Bakit Kailangan ng Taunang Serbisyo ng Outboard Motor?

Isipin mo na parang kotse ang outboard motor: kahit ilang beses mo lang ginamit sa isang summer, kailangan pa rin ng regular na maintenance para umandar nang maayos. Ang tubig sa lawa ay may dumi at minerals na pwedeng makasira sa cooling system. ‘Yung impeller, isang rubber part na parang water pump, natutuyo at nababasag kung hindi napapalitan taon-taon. Ang lower unit oil ay pwedeng mag-contaminate ng tubig, kaya sa annual service ay dini-drain namin at pinapalitan. Pati spark plugs, fuel filter, at timing ay chini-check para iwas biglaang tigil ng makina sa gitna ng lawa.

Sa HBW, sanay na sanay kami sa Mercury outboards. Bilang Mercury Marine Premier Dealer, certified technicians ang gumagawa ng service ayon sa latest standards ng Mercury. Kapag nagpa-taunang serbisyo ka sa amin, hindi lang basic lang ang ginagawa, ini-inspect din namin ang propeller, steering system, at electrical para siguradong handa ang bangka sa susunod mong labas.

## Ang Winterization: Hindi Ito Optional sa Ontario

Maraming bagong boat owner sa Greater Toronto Area, lalo na ‘yung galing sa lugar na hindi nagye-yelo, ang nagkakamaling iniisip na pwedeng iwan lang ang bangka sa garahe kapag winter. Sa Ontario, ang winterization ay hindi optional, ito ay requirement kung ayaw mong masira ang makina.

Bakit? Tuwing nagyeyelo ang temperatura, ang tubig na naiiwan sa loob ng engine block, cooling passages, at lower unit ay mag-e-expand at literal na bibiyakin ang metal. Tawag dito ay freeze damage, at ang repair nito ay kadalasang mas mahal pa sa presyo ng lumang motor. Pati fuel system ay naaapektuhan: ang gasolina na naiiwan ay nagfe-phase separate at nag-iiwan ng malagkit na residue na bumabara sa carburetor o fuel injectors. Bukod pa, ang moisture sa loob ng cylinders ay nagdudulot ng kalawang.

Dito pumapasok ang aming winterization service. Noong nakaraang season, **584 na bangka** ang ni-winterize namin, ibig sabihin, sanay na sanay na kami. Kasama sa winterization package ang:

- Pagda-drain ng lahat ng tubig mula sa engine block, exhaust, at cooling system.
- Paglalagay ng fuel stabilizer sa tangke para hindi masira ang gasolina habang nakaimbak.
- Pag-fogging ng cylinders, isang protective oil mist na pumoprotekta sa loob ng makina laban sa kalawang.
- Pagpalit ng lower unit gear oil, at pag-inspect sa seals para walang tubig na pumasok.
- Pag-check ng propeller, skeg, at anode, at pag-lubricate ng grease fittings.
- Pag-alis ng battery at pag-store nito sa safe na lugar.

Ang lahat ng ito ay ginagawa gamit ang OEM Mercury parts at procedures. Kung hindi Mercury ang outboard mo, pasensya na, sa engine repairs, **Mercury at Mercruiser lang** ang sineserbisyuhan namin. Pero kung Mercury ang dala mo, you’re in good hands.

At tandaan: sarado ang HBW mula December 1 hanggang April 1. Kaya huwag kang maghintay ng December bago mag-book. Maagang magpa-schedule para siguradong protektado ang motor bago mag-freeze.

## Spring Commissioning: Paggising ng Bangka Pagkatapos ng Taglamig

Pagkatapos ng mahabang winter, hindi pwedeng isalang agad sa lawa ang bangka nang walang preparation. Kailangan ng spring commissioning para masigurong lahat ay OK. Kasama rito ang:

- Pag-reconnect ng battery at pag-test ng charge.
- Pag-check ng engine compression at ignition system.
- Pagpalit ng engine oil (kung 4-stroke) at fuel filter.
- Pag-start ng makina sa hose para i-flush ang antifreeze o storage oil.
- Pag-inspect sa belts, hoses, at wiring na baka kinain ng daga.
- Pag-test sa steering, throttle, at emergency kill switch.

Kung kami ang nag-winterize noong fall, alam na namin ang history ng motor at mas mabilis ang commissioning. Pero kahit ikaw mismo ang nag-winterize, puwede ka pa ring magpa-spring check para sa peace of mind.

## Kailan Dapat Pumunta sa Isang Mercury-Certified Shop?

Hindi mo kailangang maghintay ng malaking sira bago pumunta sa shop. Mas mainam na maagapan bago lumala. Pumunta kaagad sa amin kung:

- Biglang nag-o-overheat ang makina habang tumatakbo.
- Parang hirap ang makina mag-accelerate o may misfire.
- May kakaibang tunog, tulad ng grinding o knocking sa lower unit.
- May oil leak o usok na hindi normal.
- Hindi consistent ang shifting ng gears.

Dahil Mercury Premier Dealer kami na may halos 60 taon nang karanasan, alam namin ang mga common issues ng Mercury outboards, pati na ang mga bagong four-stroke models. May direct access kami sa technical support ng Mercury at sa genuine parts. Ibig sabihin, mas mabilis at mas tama ang diagnosis.

Mahalagang tandaan: **ang base warranty ng Mercury ay 3 taon**. Kung under warranty pa ang motor mo, hindi ka dapat magpagawa sa hindi certified, baka ma-void ang warranty. Sa HBW, authorized warranty center kami.

## Paano Mag-book ng Serbisyo

Hindi namin pinapahirapan ang booking. Pumunta lang sa aming service page: https://hbw.wiki/service at sagutan ang form. Puwede ring tumawag o mag-text:

- 📞 Telepono: (905) 342-2153  
- 📱 Text: (647) 952-2153  

Pick-up lang ang serbisyo namin sa aming lokasyon sa Gores Landing. Hindi kami pumupunta sa bahay mo para mag-ayos, pero madaling i-trailer ang bangka papunta sa amin, halos 90 minutong biyahe mula sa Brampton, Mississauga, Scarborough, o Markham. May ethanol-free fuel kami on site, at habang naghihintay, puwede mong tingnan ang aming kasalukuyang rental fleet sa harrisboatworks.ca/rentals kung gusto mong maglaan ng oras sa lawa pagkatapos.

## Isang Matapat na Paalala Tungkol sa Wika

Ginawa namin ang gabay na ito sa Tagalog dahil gusto talaga naming matulungan ang komunidad ng mga Pilipino na mag-enjoy sa boating sa Rice Lake nang walang pangamba. Kakaunti lang ang resource na ganito, at gusto naming maramdaman ninyo na welcome kayo sa mundo ng boating sa Ontario.

Pero kailangan naming maging diretso: ang aming team ay nagsisilbi sa English. Wala kaming staff na fluent sa Tagalog. Kung hindi ka kumpiyansa sa English, huwag mag-alala, magsama ka ng kaibigan o kapamilya na pwedeng mag-translate, o gumamit ng translation app sa telepono. Magiging matiyaga kami, mag-uusap nang dahan-dahan, at sisiguraduhing magkakaintindihan tayo. Hindi namin hahayaang maging hadlang ang wika para makuha mo ang tamang serbisyo para sa bangka mo.

## FAQs (Mga Madalas Itanong)

**Saan makakahanap ng mekaniko ng bangka sa Toronto?**  
Ang HBW ay nasa Gores Landing, malapit sa Rice Lake, mga 90 minutong biyahe mula Brampton, Mississauga, Scarborough, at Markham. Walang malapit na shop sa loob ng Toronto na mare-rekomenda namin, pero maraming may-ari ng Mercury ang pumipiling mag-drive papunta sa amin dahil sa aming kadalubhasaan. Kung gusto mong makasigurado sa certified service, puntahan kami.

**May marine mechanic ba na Pilipino sa Toronto?**  
Wala pong Pilipinong mechanic sa HBW. Ang lahat ng aming technician ay bihasa sa Mercury pero ang lengguwahe ng shop ay English. Ang serbisyo namin ay sa English, kaya magdala ng kasamang marunong mag-English o gumamit ng translation app; matiyaga naming aasikasuhin ang kailangan mo.

**Paano i-winterize ang bangka?**  
Ang professional winterization ay binubuo ng pag-drain ng tubig, pag-fog sa cylinders, paglalagay ng fuel stabilizer, pagpalit ng gear oil, at marami pang hakbang para protektahan ang makina sa lamig. Puwede mong gawin ito nang sarili kung may experience ka, pero kung bago ka pa lang, mas safe na ipagawa sa certified shop tulad ng HBW. Tingnan ang aming winterization service para sa detalyadong breakdown.

**Saan ang winter storage ng bangka sa Ontario?**  
Nag-aalok ang HBW ng winter storage sa aming marina sa Gores Landing, at puwedeng isabay ito sa winterization ng motor. Napupuno ang storage tuwing fall, kaya mag-book nang maaga bago ang December 1. Magtanong sa https://hbw.wiki/service.

**Paano ayusin ang Mercury outboard?**  
Kung Mercury o Mercruiser ang motor mo, dalhin mo sa amin. Umpisahan namin ito ng computer diagnostic kung applicable, visual inspection, at pag-check ng fuel, spark, at compression. Certified technicians ang gagawa, at purong Mercury parts lang ang gagamitin. Kung may warranty ka, protektado ito kapag sa amin ka nagpagawa.

**Saan ang pagawaan ng motor ng bangka malapit sa Mississauga?**  
Walang partikular na shop sa Mississauga na mare-rekomenda namin. Ang HBW ay mula sa Gores Landing, mga 90 minuto ang biyahe, pero marami kaming customer na galing Mississauga dahil sa kumpiyansa nila sa aming Mercury expertise. Kung handa kang mag-drive, welcome ka rito.

**Puwede ba akong makakuha ng serbisyo sa Tagalog sa HBW?**  
Hindi po. Ang aming team ay nagsisilbi sa English lamang. Pero huwag mahiya: magsama ng kaibigan o pamilya na marunong mag-Ingles, o gumamit ng translation app. Magiging matiyaga kami sa pagpapaliwanag hanggang maintindihan mo nang lubos.

## Makipag-ugnayan sa Amin

Handa na ang bangka mo para sa summer? O kailangan na ng winterization bago humaba ang gabi? Anuman ang season, nandito ang HBW para tulungan kang ma-enjoy ang Rice Lake nang may peace of mind.

- 📍 5369 Harris Boat Works Rd, Gores Landing, ON K0K 2E0
- 📞 Telepono: (905) 342-2153
- 📱 Text: (647) 952-2153
- 🔧 Mag-book ng serbisyo: https://hbw.wiki/service

Mula pa noong 1947, nagsisilbi na kami sa mga boat owner sa Ontario. Family-owned, Mercury-certified, at kayang maghintay kahit may kaunting translation challenge. Sama-sama nating siguraduhing laging handang umandar ang bangka mo.`
  }
];

export function getTagalogArticleBySlug(slug: string): Wave1Article | undefined {
  return tagalogBlogArticles.find((a) => a.slug === slug);
}

export function getPublishedTagalogArticles(): Wave1Article[] {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return tagalogBlogArticles.filter(article => {
    const publishDate = new Date(article.publishDate || article.datePublished);
    publishDate.setHours(0, 0, 0, 0);
    return publishDate <= today;
  });
}
